# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

shopt -s histappend

export BLASTDB=/databases/blast_db/

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line to automatically activate QIIME but note that
# this will override standard tools with possibly older versions such as R
# and mothur.
# source /home/qiime/qiime_current/activate.sh
