# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

shopt -s histappend

export BLASTDB=/databases/blast_db/

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
source /home/qiime/qiime_current/activate.sh
