%define samtools_version 0.1.18

Name:           perl-Bio-SamTools
Version:        1.36
Release:        2%{?dist}
Summary:        Bio::SamTools Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Bio-SamTools/
Source0:        http://www.cpan.org/authors/id/L/LD/LDS/Bio-SamTools-%{version}.tar.gz
Source1:        http://downloads.sourceforge.net/samtools/samtools-%{samtools_version}.tar.bz2
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 0:5.008
BuildRequires:  perl(Bio::Root::Version) >= 1.006009001
BuildRequires:  perl(ExtUtils::CBuilder)
BuildRequires:  perl(Module::Build)
BuildRequires:	samtools-libs
BuildRequires:	samtools-devel
BuildRequires:	zlib-devel
BuildRequires:	ncurses-devel
#Requires:       perl(Bio::Root::Version) >= 1.006009001
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
To compile this module, you must first download, unpack and compile
SAMtools 0.1.4 or higher in some accessible directory. FOR SAMTOOLS VERSION
0.1.4, YOU MUST RUN "make -f makefile.generic" IN THE DISTRIBUTION
DIRECTORY IN ORDER TO CREATE THE REQUIRED libbam.a LIBRARY FILE. For other
versions, just "make" will usually work.

%prep
%setup -q -n Bio-SamTools-%{version} -a1

%build
cd samtools-%{samtools_version}
make %{_smp_mflags} CFLAGS=-fPIC
mkdir -p %{_tmppath}/bamlib
/bin/cp *.h %{_tmppath}/bamlib
/bin/cp *.a %{_tmppath}/bamlib
cd ..

export SAMTOOLS=%{_tmppath}/bamlib 
%{__perl} Build.PL installdirs=vendor optimize="$RPM_OPT_FLAGS"
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Bio-SamTools-1.33-tamline.diff c_bin Changes DISCLAIMER LICENSE makefile META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Bio*
%{_mandir}/man3/*
/usr/bin/bam2bedgraph
/usr/bin/bamToGBrowse.pl
/usr/bin/chrom_sizes.pl
/usr/bin/genomeCoverageBed.pl

%changelog
* Tue Nov 06 2012 Carl Jones <carl@biomatters.com> 1.36-2
- Build samtools and put required libs into temporary location

* Mon Nov 05 2012 Carl Jones <carl@biomatters.com> 1.36-1
- Specfile autogenerated by cpanspec 1.78.
