#!/bin/bash
yum clean all &>/dev/null
yum -q -y -x libXfixes -x libXfixes-devel -x kernel -x kernel-devel -x kernel-firmware -x kernel-headers upgrade &>/dev/null
yum -q -y groupinstall NZGL &>/dev/null
