#!/bin/bash

# rm coverage.hist test*

set -e

module load openmpi-x86_64

# abyss-pe k=25 name=test in='reads1.fastq reads2.fastq'
abyss-pe np=4 k=25 name=test in='reads1.fastq reads2.fastq'

cmp -s reference-stats.md test-stats.md > /dev/null
if [ $? -eq 1 ]; then
  exit 1
fi

rm coverage.hist test*

exit 0
