#!/bin/bash

function usage() {
	cat << EOF
Usage: ${0} [-u] [-g]

	-u Username
	-g Project group
EOF
}

if [ $# -lt 3 ]; then
	usage
	exit 1
fi

while getopts u:g: flag; do
	case $flag in
		u) USER=$OPTARG
		   ;;
		g) GROUP=$OPTARG
		   ;;
		?)
		   usage
		   exit 1
		   ;;
	esac
done

# Create project directories

mkdir /archive/$GROUP /active/$GROUP /scratch/$GROUP
chmod 770 /active/$GROUP /scratch/$GROUP
chmod 550 /archive/$GROUP
chown $USER:$GROUP /archive/$GROUP /active/$GROUP /scratch/$GROUP

echo "Created /archive/${GROUP}, /active/${GROUP}, /scratch/${GROUP}"

# Create user home directory

mkdir /home/$USER
cp /home/shane/.bashrc /home/$USER
cp /home/shane/.bash_profile /home/$USER
chmod 700 /home/$USER
mkdir -p /home/$USER/project/$GROUP
ln -s /archive/$GROUP /home/$USER/project/$GROUP/archive
ln -s /active/$GROUP /home/$USER/project/$GROUP/active
ln -s /scratch/$GROUP /home/$USER/project/$GROUP/scratch
chown -R $USER:$GROUP /home/$USER

echo "Created /home/${USER} and project symlinks"
