#!/bin/bash

function usage() {
	cat << EOF
Usage: ${0} -u -g [-b]

	-u Username
	-g Project group
	-b BioIT contract (optional)

Note: This uses setfacl to allow users access to the selected project
EOF
}

if [ $# -lt 3 ]; then
	usage
	exit 1
fi

USERNAME=
GROUP=
BIOIT=

while getopts u:g:b: flag; do
        case $flag in
                u) USERNAME=$OPTARG
                   ;;
                g) GROUP=$OPTARG
                   ;;
                b) BIOIT=$OPTARG
                   ;;
                ?)
                   usage
                   exit 1
                   ;;
        esac
done

if [ -z "$USERNAME" ] || [ -z "$GROUP" ]; then
    usage
    exit 1
fi

if ! id -u "$USERNAME" &>/dev/null ; then
   echo "'$USERNAME' is not an existing user name"
   exit 1
fi

# Purge sssd cache to ensure new usergroup membership is updated

/usr/sbin/sss_cache -u $USERNAME

if ! id -Gn "$USERNAME" | grep "$GROUP" &>/dev/null ; then
   echo "'$GROUP' is not a group containing '$USERNAME'"
   exit 1
fi

if [ ! -z "$BIOIT" ]; then
  if ! id -Gn "$USERNAME" | grep "$BIOIT" &>/dev/null ; then
    echo "'$BIOIT' is not a group containing '$USERNAME'"
    exit 1
  fi
fi

if [ -z "$BIOIT" ]; then
  if [ ! -d "/archive/$GROUP" ]; then
    echo "/archive/${GROUP} etc don't exist, aborting"
    exit 1
  fi
  cd /archive
  setfacl -m u:$USERNAME:r -d -R $GROUP
  find $GROUP -type d -exec setfacl -m u:$USERNAME:rx -d {} \;
  if [ -d "/active/$GROUP" ]; then
    cd /active
    setfacl -m u:$USERNAME:rw -d -R $GROUP
    find $GROUP -type d -exec setfacl -m u:$USERNAME:rwx -d {} \;
  fi
  if [ -d "/scratch/$GROUP" ]; then
    cd /scratch
    setfacl -m u:$USERNAME:rw -d -R $GROUP
    find $GROUP -type d -exec setfacl -m u:$USERNAME:rwx -d {} \;
  fi
else
  if [ ! -d "/archive/$BIOIT" ]; then
    echo "/archive/${BIOIT} etc don't exist, aborting"
    exit 1
  fi
  if [ ! -d "/archive/$BIOIT/$GROUP" ]; then
    echo "/archive/${BIOIT}/${GROUP} etc don't exist, aboring"
    exit 1
  fi
  cd /archive
  # Note these aren't recursive to prevent setting access to all
  # subprojects
  setfacl -m u:$USERNAME:r -d $BIOIT
  find $BIOIT -type d -exec setfacl -m u:$USERNAME:rx -d {} \;
  if [ -d "/active/$BIOIT/$GROUP" ]; then
    cd /active
    setfacl -m u:$USERNAME:rw -d $BIOIT
    find $BIOIT -type d -exec setfacl -m u:$USERNAME:rwx -d {} \;
  fi
  if [ -d "/scratch/$BIOIT/$GROUP" ]; then
    cd /scratch
    setfacl -m u:$USERNAME:rw -d $BIOIT
    find $BIOIT -type d -exec setfacl -m u:$USERNAME:rwx -d {} \;
  fi
  if [ -d "/archive/$BIOIT/$GROUP" ]; then
    cd /archive/$BIOIT
    setfacl -m u:$USERNAME:r -d -R $GROUP
    find $GROUP -type d -exec setfacl -m u:$USERNAME:rx -d {} \;
  fi
  if [ -d "/active/$BIOIT/$GROUP" ]; then
    cd /active/$BIOIT
    setfacl -m u:$USERNAME:rw -d -R $GROUP
    find $GROUP -type d -exec setfacl -m u:$USERNAME:rwx -d {} \;
  fi
  if [ -d "/scratch/$BIOIT/$GROUP" ]; then
    cd /scratch/$BIOIT
    setfacl -m u:$USERNAME:rw -d -R $GROUP
    find $GROUP -type d -exec setfacl -m u:$USERNAME:rwx -d {} \;
  fi
fi
