#!/bin/bash
set -e

picard_dir='/usr/share/java/picard'


function cleanup() {
	for file in Asperg.sam new.sam; do
		[ -e ${file} ] && rm -f ${file}
	done
	return 0
}

cleanup
java -jar ${picard_dir}/picard.jar CreateSequenceDictionary OUTPUT=Asperg.sam R=Asperg.fasta
java -jar ${picard_dir}/picard.jar SortSam INPUT=Asperg.sam OUTPUT=new.sam SORT_ORDER=unsorted
cleanup
