--- makefile.orig	2013-10-03 07:27:33.419083045 +1300
+++ makefile	2013-10-03 07:30:12.461980641 +1300
@@ -28,7 +28,7 @@
 	#CXX = g++44
 	
 	#if you are a mac user use the following line
-	TARGET_ARCH += -arch x86_64
+	# TARGET_ARCH += -arch x86_64
 	
 	#if you using cygwin to build Windows the following line
 	#CXX = x86_64-w64-mingw32-g++
@@ -37,7 +37,7 @@
  	#TARGET_ARCH += -m64 -static
 
 	#if you are a linux user use the following line
-	#CXXFLAGS += -mtune=native -march=native 
+	CXXFLAGS += -mtune=native -march=native 
 	
 	CXXFLAGS += -DBIT_VERSION 
 endif
