--- Makefile.orig	2016-04-20 08:45:02.980918607 +1200
+++ Makefile	2016-04-20 08:45:29.139183238 +1200
@@ -11,11 +11,11 @@
 64BIT_VERSION ?= yes
 OPTIMIZE ?= yes
 USEREADLINE ?= yes
-USEBOOST ?= yes
+USEBOOST ?= no
 BOOST_LIBRARY_DIR="\"Enter_your_boost_library_path_here\""
 MOTHUR_FILES="\"Enter_your_default_path_here\""
 RELEASE_DATE = "\"4/18/2016\""
-VERSION = "\"1.37.1\""
+VERSION = "\"1.37.2\""
 
 ifeq  ($(strip $(64BIT_VERSION)),yes)
     CXXFLAGS += -DBIT_VERSION
