Name:		SolexaQA++
Version:	3.0
Release:	2%{?dist}
Summary:	Calculates quality statistics and creates visual representations of data quality from FASTQ files.
Group:		Applications/Engineering
License:	GPLv3
URL:		http://solexaqa.sourceforge.net/
Source0:	%{name}_v%{version}.zip
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:	x86_64

%description
SolexaQA is a Perl-based software package that calculates quality statistics and creates visual representations of 
data quality from FASTQ files generated by Illumina second-generation sequencing technology (“Solexa”).

%prep
%setup -q -c

%build

%install
rm -rf %{buildroot}

mkdir -p %{buildroot}/%{_bindir}
install -m 0755 %{name}_v%{version}/Linux_x64/%{name} %{buildroot}/%{_bindir}

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
/usr/bin/%{name}

%changelog
* Tue Aug 12 2014 Shane Sturrock <shane@biomatters.com> - 3.0-2
- Minor bug fix release
* Thu Aug 7 2014 Shane Sturrock <shane@biomatters.com> - 3.0-1
- Initial release of C++ based version
- Analysis (previously available as SolexaQA.pl): general performance
  improvements; the software can now process FASTQ files with variable read
  lengths, is compatible with Ion Torrent files (–t option), and .gz
  compressed files (Linux and OS X releases only). Minor cosmetic changes to
  graphs and command-line output have also been made.
- DynamicTrim: general performance improvements (up to 100% faster); bug fix
  for truncated graphs on variable length reads; compatible with .gz
  compressed files (Linux and OS X releases only); new progress bar in
  command-line output.
- LengthSort: paired-end mode includes a new option (–c) to remove
  non-matching reads from the two FASTQ files prior to processing; compatible
  with .gz compressed files (Linux and OS X releases only); new histogram
  output; new progress bar in command-line output.

