#!/bin/bash

mailto=carl@biomatters.com

tmp=$(mktemp)

cd upstream_package_check
./update_recorded_version.sh --cron
./upstream_package_check.sh > ${tmp}

if [ -s ${tmp} ]; then
	cat ${tmp} | mail -s 'Upstream package check' ${mailto}
fi

rm -f ${tmp}
exit 0
