#!/bin/bash

log_dir='/var/log/biomatters/report'
bin='/root/nzgl/bin'

mkdir -p ${log_dir}
log=${log_dir}/$(date +%Y-%m-%d).log

# Don't over write existing log
if [ -e ${log} ]; then
	echo "Error: Log ${log} already exists."
	exit 1
fi

redhat_updates=$(${bin}/list_yum_updates today)
failed_tests=$(${bin}/test_apps -a -r | sed 's/ *$//g')
upstream_updates=$(${bin}/version_check -a -r | sed 's/ *$//g')

{
[ -n "${redhat_updates}" ] && echo "redhat_updates='${redhat_updates}'"
[ -n "${upstream_updates}" ] && echo "upstream_updates='${upstream_updates}'"
[ -n "${failed_tests}" ] && echo "failed_tests='${failed_tests}'"
} > ${log}
