#!/bin/bash

log_dir='/var/log/biomatters'
log="pkg-update-$(date +%Y-%m-%d).log"
repos='rhel-x86_64-server-6 rhel-x86_64-server-optional-6'
repo_base='/var/www/nzgl'

[ "${1}" == "--report" ] && report='true'

set -e

mkdir -p ${log_dir}

for repo in ${repos}; do
	cd ${repo_base}/${repo}/getPackage
	find . -type f -ctime -1 -printf "%f\n" > ${log_dir}/${log}
done

[ -n "${report}" ] && cat ${log_dir}/${log}
exit wc -l ${log_dir}/${log}
