.ds ]W %
.ds ]L
.hy 0
.nh
.na
.TH egoconfig 8 "June 2007   Platform EGO 1.2.2"
.br

.SH NAME
\fBegoconfig\fR - Configures Platform EGO hosts.

.SH Synopsis
.BR
.PP
 egoconfig subcommand [options]  egoconfig -h  egoconfig -V 
.SH Description
.BR
.PP

.PP
Use the egoconfig command to join a host to the cluster, set the list of master 
candidates and the failover priority, and add hosts to or remove hosts from the 
ManagementHosts resource groups, or set other configuration options.

.PP
This is an administrative command. You must be logged on as cluster administrator 
to issue this command.

.SS -h
.BR
.PP

.PP
Outputs command usage and exits.

.SS -V
.BR
.PP

.PP
Prints product version to stderr and exits.

.SH Subcommand synopsis
.BR
.PP
 addresourceattr [resource resource_name] [resourcemap value*resource_name] ...  join master_name [-f]  masterlist host_name[,host_name, ...]  mghost shared_top [-f]  mghost shared_top user_account password [-f]  mghost lsf [-f]  mghost lsf user_account password [-f]  mghost soam [-f]  mghost soam [user_account] [password] [-f]  setbaseport base_port_no  setlicense license_file  unsetmghost [-f] 
.SH addresourceattr [resource resource_name][...]
.BR
.PP

.PP
Adds a resource attribute tag to the parameter EGO_LOCAL_RESOURCES in 
ego.conf on the local host. The attribute tag is later referenced when you create a 
resource group and want to add hosts to it that share the same resource attribute.

.SS resourcemap
.BR
.PP

.PP
Keyword required by EGO_LOCAL_RESOURCES to signify that the name of the 
resource attribute tag is numeric. The name is preceded by a numeric value to form 
a name-value pair.

.SS resource
.BR
.PP

.PP
Keyword required by EGO_LOCAL_RESOURCES to signify that the name of the 
resource attribute tag is boolean.

.SS resource_name
.BR
.PP

.PP
Specifies the name of the resource attribute tag that identifies this type of host. For 
example, the resource attribute tag scvg could be later used to create a resource 
group for scavenging-capable hosts.

.SH join master_name [-f]
.BR
.PP

.PP
For use on UNIX only. Adds the local UNIX host to the cluster that has the specified 
master host.

.SS master_name 
.BR
.PP

.PP
Specifies the host name of the master host.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.SH masterlist host_name[,host_name, ...]
.BR
.PP

.PP
Specifies the list of master candidates, starting with the master host, and including 
all of the candidates, in the order of failover priority.

.SS  host_name 
.BR
.PP

.PP
Specifies the name of the master host and each of the master candidates. Ensure that 
you do not specify compute hosts in this list.

.PP
caution:  

.PP
Be sure to include all master candidates in the list when you issue this command, as 
issuing this command overwrites the existing list.

.SH mghost shared_top [-f]
.BR
.PP

.PP
For use on UNIX. Specifies to ignore the local configuration directory and look in 
the shared location for the configuration information and common files so the 
management hosts use a common set of files. Issuing this command adds this host 
to the management hosts resource group.

.PP
After issuing this command, you need to source your environment. Running this 
command creates an entry for the local host in ego.cluster.clustername.

.SS shared_top
.BR
.PP

.PP
Specifies the path to the shared file location where configuration information is 
accessed by the management hosts in the cluster.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.SH mghost shared_top user_account password [-f]
.BR
.PP

.PP
For use on Windows. Specifies to ignore the local configuration directory and look 
in the shared location for the configuration information and common files so the 
management hosts use a common set of files. Issuing this command adds this host 
to the management hosts resource group.

.PP
Issuing this command changes the behavior of Windows services on this host to 
run under the cluster administrator account rather than the local service account. 
Running this command creates an entry for the local host in 
ego.cluster.clustername.

.SS shared_top
.BR
.PP

.PP
Specifies the path to the shared file location where configuration information is 
accessed by the management hosts in the cluster.

.SS user_account
.BR
.PP

.PP
Specifies the user account under which to run. Must be a valid user account that has 
been assigned the role of CLUSTERADMIN. The format is DOMAIN\\user_name.

.SS password
.BR
.PP

.PP
Specifies the password to use to authenticate the user account.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.SH mghost lsf [-f]
.BR
.PP

.PP
For use on UNIX. Use this command when adding Platform LSF to an existing 
EGO cluster. Specifies to ignore the local LSF configuration directory and use the 
EGO shared directory instead. Issue this command on all management hosts so LSF 
can use shared location configurations.

.PP
After issuing this command, you need to source your environment.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.SH mghost lsf user_account password [-f]
.BR
.PP

.PP
For use on Windows. Use this command when adding Platform LSF to an existing 
EGO cluster. Specifies to ignore the local LSF configuration directory and use the 
EGO shared directory instead. Issue this command on all management hosts so LSF 
can use shared location configurations.

.PP
After issuing this command, you need to relaunch another DOS command prompt.

.SS user_account
.BR
.PP

.PP
Specifies the user account under which to run. Must be a valid user account that has 
been assigned the role of CLUSTERADMIN. The format is DOMAIN\\user_name.

.SS password
.BR
.PP

.PP
Specifies the password to use to authenticate the user account.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.SH mghost soam [-f]
.BR
.PP

.PP
For use on UNIX. Use this command when adding Platform Symphony to an 
existing EGO cluster. Specifies to ignore the local Symphony configuration 
directory and use the EGO shared directory instead. Issue this command only on 
the master host so that Symphony can use shared location configurations.

.PP
After issuing this command, you need to source your environment.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.SH mghost soam [user_account] [password] [-f]
.BR
.PP

.PP
For use on Windows. Use this command when Platform Symphony and Platform 
EGO are installed together. Specifies to ignore the local Symphony configuration 
directory and use the EGO shared directory instead. Issue this command only on 
the master host so that Symphony can use shared location configurations.

.SS user_account
.BR
.PP

.PP
Specifies the user account under which to run. Must be a valid user account that has 
been assigned the role of CLUSTERADMIN. The format is DOMAIN\\user_name.

.SS password
.BR
.PP

.PP
Specifies the password to use to authenticate the user account.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.SH setbaseport base_port_no
.BR
.PP

.PP
Changes the port number for the EGO_LIM service or daemon to the specified port 
number.

.PP
caution:  

.PP
Shut down the cluster before issuing this command.

.PP
The remaining system port numbers are also changed as a result of issuing this 
command.

.SS base_port_no
.BR
.PP

.PP
Specifies an unused port number. The default base connection port is 7869. 
Platform EGO always uses four consecutive ports starting from the base port. By 
default, Platform EGO uses ports 7869-7872.

.SH setlicense license_file
.BR
.PP

.PP
For use on UNIX only. Copies the specified license file into the EGO configuration 
directory and updates the configuration file ego.conf with the name and location 
of the license file.

.SS license_file
.BR
.PP

.PP
Specifies the full path to the license file including the file name.

.SH unsetmghost [-f]
.BR
.PP

.PP
Demotes the local management host to a compute host.

.PP
Specifies to look in the local configuration directory for configuration information 
and common files. This command cannot be run on the master host.

.PP
Before running this command, ensure the host's lim is not running (you may need 
to shut down the host first). Be sure to restart the master host after running this 
command for the change to take effect. Running this command removes the host 
entry from ego.cluster.cluster_name.

.SS -f
.BR
.PP

.PP
Suppresses confirmation of the command.

.PP
Use this option when running this command from a script.

.\" Generated by Quadralay WebWorks Publisher 2003 for FrameMaker 8.0.5.1556
.\" Generated on June 21, 2007 
.\" Man section: 8 
.\" File Name: egoconfig 
.\" Based on template structured_wwp8_man_page
.\" Copyright 1994-2007 Platform Computing Corporation
