
.ad l

.ll 72

.TH perfsetrc 8 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBperfsetrc.sh\fR
.sp 2
   Configures automatic startup of the LSF Reporting (PERF)
   daemons on a UNIX host.
.sp 2

.sp 2 .SH "Synopsis"
\fBSynopsis\fR
.sp 2
perfsetrc.sh
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   This is an administrative command. You must be logged on as
   root to issue this command.
.sp 2
   Configures a UNIX host to allow automatic startup of PERF
   daemons on the machine when a system reboot command is issued.
   Creates the file perf under the system startup directory.
.sp 2
   For ease of administration, you should enable automatic
   startup. This starts PERF daemons automatically when the host
   restarts.
.sp 2
   If you do not configure hosts to start automatically, PERF
   daemons must be started manually.
.sp 2
   Run the command on the PERF host to control the following PERF
   services: loader controller (plc), job data transformer
   (jobdt), and data purger (purger). Run the command on the
   Derby database host to control the Derby database service
   (derbydb).
.sp 2
