
.ad l

.ll 72

.TH pmcsetrc 8 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBpmcsetrc.sh\fR
.sp 2
   Configures automatic startup of the HPC Portal on a UNIX host.
.sp 2

.sp 2 .SH "Synopsis"
\fBSynopsis\fR
.sp 2
pmcsetrc.sh
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Configures a UNIX host to allow automatic startup of HPC
   Portal on the machine when a system reboot command is issued.
   Creates the file pmc under the system startup directory.
.sp 2
   This is an administrative command. You must be logged on as
   root to issue this command.
.sp 2
   For ease of administration, you should enable automatic
   startup. This starts HPC Portal automatically when the host
   restarts.
.sp 2
   If you do not configure hosts to start automatically, HPC
   Portal must be started manually.
