
.ad l

.ll 72

.TH pversions_win 8 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBpversions (Windows)\fR
.sp 2
   Windows version of the command: displays the version
   information for Platform products installed on a Windows host.
.sp 2

.sp 2 .SH "Synopsis"
\fBSynopsis\fR
.sp 2
pversions [product_name]
.sp 2
pversions -h
.sp 2
pversions -V
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Displays the version and patch level of a Platform product
   installed on a Windows host, and the list of patches
   installed.
.sp 2 .SH "Options"
\fBOptions\fR
.sp 2
   \fB\fIproduct_name\fB\fR
.br
               Specify the Platform product for which you want
               version information. Specify one of the following:
.sp 2
                 o  
                     EGO—to see version information for Platform
                     EGO
.sp 2
                 o  
                     Symphony—to see version information for
                     Platform Symphony and Symphony Developer’s
                     Edition
.sp 2
                 o  
                     LSF—to see version information for Platform
                     LSF
.sp 2
   \fB-h\fR
.br
               Prints command usage to stderr and exits from the
               software.
.sp 2
   \fB-V\fR
.br
               Prints product version to stderr and exits.
.sp 2
