
.ad l

.ll 72

.TH wguser 8 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBwguser\fR
.sp 2
   modifies user accounts for an entire Microsoft Windows
   workgroup
.sp 2

.sp 2 .SH "Synopsis"
\fBSynopsis\fR
.sp 2
wguser [-r] user_name ...
.sp 2
wguser [-h]
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
      \fBCAUTION: \fR
.sp 2
         You must run this command on a host in a Microsoft
         Windows workgroup. You should have administrative
         privileges on every host in the workgroup.
.sp 2
   Modifies accounts on every host in the workgroup that you have
   administrative privileges on.
.sp 2
   By default, prompts for a default password to use for all of
   the accounts, and then creates the specified user accounts on
   each host, if they do not already exist.
.sp 2
   Use -r to remove accounts from the workgroup.
.sp 2 .SH "Options"
\fBOptions\fR
.sp 2
   \fB-r\fR
.br
               Removes the specified user accounts from each
               host, if they exist.
.sp 2
   \fB\fIuser_name\fB ...\fR
.br
               Required. Specifies the accounts to add or remove.
.sp 2
   \fB-h\fR
.br
               Prints command usage to stderr and exits.
.sp 2 .SH "Output"
\fBOutput\fR
.sp 2
   For each host in the workgroup, returns the result of the
   operation (SUCCESS or FAILED).
