#!/bin/bash

# Based on sample_data/test_Trinity_Assembly/runMe.sh script shipped with Trinity

set -e

if [ -e reads.right.fq.gz ] && [ ! -e reads.right.fq ]; then
    gunzip -c reads.right.fq.gz > reads.right.fq
fi

if [ -e reads.left.fq.gz ] && [ ! -e reads.left.fq ]; then
    gunzip -c reads.left.fq.gz > reads.left.fq
fi

#######################################################
##  Run Trinity to Generate Transcriptome Assemblies ##
#######################################################

## use jellyfish
/usr/bin/Trinity.pl --seqType fq --JM 2G --left reads.left.fq --right reads.right.fq --SS_lib_type RF --CPU 4 # --bowtie_comp

##### Done Running Trinity #####

#if [ ! $* ]; then
#    exit 0
#fi
#
#sleep 2


###########################################
# use RSEM to estimate read abundance  ####
###########################################

sleep 2

/usr/libexec/trinityrnaseq/util/RSEM_util/run_RSEM_align_n_estimate.pl --transcripts trinity_out_dir/Trinity.fasta --seqType fq --left reads.left.fq --right reads.right.fq --SS_lib_type RF

###### Done running RSEM ########

# Cleanup
/bin/rm -rf trinity_out_dir
/bin/rm reads.right.fq reads.left.fq
/bin/rm -rf TRANS* RSEM*

###### Cleaned up temporary files #######

# Based on test_Trinity_Coding_Extraction/runMe.sh

if [ -e Trinity.fasta.gz ] && [ ! -e Trinity.fasta ]
then
    gunzip -c Trinity.fasta.gz > Trinity.fasta
fi

/usr/libexec/trinityrnaseq/trinity-plugins/transdecoder/TransDecoder -t Trinity.fasta -m 50

####### Clean up temp files #######

/bin/rm Trinity.fasta
#/bin/rm base_freqs.dat best_candidates.* hexamer.scores longest_orfs.* Trinity.fasta

# Taken from test_full_edgeR_pipeline/runMe.sh

/usr/libexec/trinityrnaseq/util/run_Trinity_edgeR_pipeline.pl --samples_file samples_n_reads_decribed.txt --genes_too

# Cleanup
/bin/rm -rf trinity_out_dir
/bin/rm reads.ALL.right.fq reads.ALL.left.fq
/bin/rm -rf TRANS* RSEM*
/bin/rm -rf ds_rep1* hs_rep1* log_rep1* plat_rep1* Trinity_trans* Trinity.trans_lengths.txt __tmp_runTMM.R edgeR_trans
/bin/rm Trinity_components.counts.matrix* Trinity.components_lengths.txt 
/bin/rm -rf edgeR_components/
/bin/rm -rf collectl
/bin/rm -rf Trinity.fasta.transdecoder.* transdecoder.tmp.*

exit 0
