Name:		solexaqa
Version:	2.0
Release:	1%{?dist}
Summary:	Calculates quality statistics and creates visual representations of data quality from FASTQ files.
Group:		Applications/Engineering
License:	GPLv3
URL:		http://solexaqa.sourceforge.net/
Source0:	SolexaQA_v.%{version}.zip
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:	noarch
Requires:	matrix2png

%description
SolexaQA is a Perl-based software package that calculates quality statistics and creates visual representations of 
data quality from FASTQ files generated by Illumina second-generation sequencing technology (“Solexa”).

%prep
%setup -q -c

%build

%install
rm -rf %{buildroot}

mkdir -p %{buildroot}/%{_bindir}
install -m 0755 SolexaQA.pl %{buildroot}/%{_bindir}

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
/usr/bin/SolexaQA.pl

%changelog
* Mon Dec 17 2012 Carl Jones <carl@biomatters.com> - 2.0-1
- New upstream release
* Fri Aug 09 2012 Carl Jones <carl@biomatters.com> - 1.13-2
- Fix source file
* Fri Aug 03 2012 Carl Jones <carl@biomatters.com> - 1.13-1
- Initial build.
