#!/bin/bash

if [ ! -d example/ ]; then
	echo "bowtie2 tests need example/ directory from bowtie2 source package."
	exit 1
fi

set -e
bowtie2-build example/reference/lambda_virus.fa lambda_virus
bowtie2 -x lambda_virus -U example/reads/reads_1.fq -S eg1.sam
bowtie2 -x lambda_virus -1 example/reads/reads_1.fq -2 example/reads/reads_2.fq -S eg2.sam
bowtie2 --local -x lambda_virus -U example/reads/longreads.fq -S eg3.sam
bowtie2 -x lambda_virus -1 example/reads/reads_1.fq -2 example/reads/reads_2.fq -S eg2.sam
samtools view -bS eg2.sam > eg2.bam
samtools sort eg2.bam eg2.sorted
samtools mpileup -uf example/reference/lambda_virus.fa eg2.sorted.bam | bcftools view -bvcg - > eg2.raw.bcf
