.TH "glb_init_all" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glb_init_all \- glb_init_all 
Initializes and establishes a connection with all License Scheduler daemons.
.PP
\fBglb_init_all\fP is a routine that initializes and establishes a connection with all License Scheduler daemons specified in lsf.licensescheduler. This is useful when there are multiple License Scheduler master and slave daemons running for failover purposes.
.PP
\fB #include <glb/glb.h>\fP
.PP
\fB link_t *glb_init_all()\fP
.PP
\fB typedef struct link_t { 
.br
 int num; 
.br
 void *ptr; 
.br
 struct link_t *next 
.br
 };\fP
.PP
\fB \fP
.PP
.SH "Parameters:"
\fInone\fP 
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
*link_t 
.br
 A linked list of License Scheduler daemon handles that \fBglb_init_all\fP initialises and connects to.
.PP
.SH "Errors:" 
.PP
On failure, glberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
LSF_CONFDIR/lsf.licensescheduler
.PP
.SH "See also:"
\fBglb_close_all\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
