.TH "glb_perror" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glb_perror \- glb_perror 
Prints LSF License Scheduler error messages.
.PP
\fBglb_perror\fP is a library routine for printing LSF License Scheduler error messages corresponding to the reported error number
.PP
\fB #include <glb/glb.h>\fP
.PP
\fB void glb_perror (const char *msg) \fP
.PP
.SH "Parameters:"
\fI*msg\fP The user-defined message. This is printed in front of the error message and is separated from the error message by a colon.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
none
.PP
.SH "Errors:" 
.PP
Systems that conform to the Single UNIX specification are not required to detect error conditions for this function.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
none
.PP
.SH "See also:"
\fBglb_info\fP 
.PP
\fBglb_jobinfo\fP 
.PP
\fBglb_perror\fP 
.PP
\fBglb_userinfo\fP 
.PP
\fBglb_workloadinfo\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
