.TH "glblib" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glblib \- glblib 
Application Programming Interface (API) library functions for GLB
.PP
.SH "Note:"
.PP
All GLBLIB APIs require that the batch header file <glb/glb.h> be included.
.PP
.SH "Files:" 
.PP
LSF_CONFDIR/lsf.licensescheduler
.PP
.SH "See also:"
\fBglb_close_all\fP 
.PP
\fBglb_groupinfolist\fP 
.PP
\fBglb_info\fP 
.PP
\fBglb_init_all\fP 
.PP
\fBglb_jobinfo\fP 
.PP
\fBglb_param\fP 
.PP
\fBglb_perror\fP 
.PP
\fBglb_userinfo\fP 
.PP
\fBglb_workloadinfo\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
