.TH "ls_getmastername" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls_getmastername \- ls_getmastername 
Returns the name of the host running the local load sharing cluster's master LIM.
.PP
This routines provides access to LSF cluster configuration information.
.PP
\fBls_getmastername\fP returns the name of the host running the local load sharing cluster's master LIM.
.PP
\fB#include <lsf/lsf.h> 
.br
 char *ls_getmastername(void)\fP
.PP
.SH "Parameters:"
\fInone\fP 
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
char *:A pointer to static space holding master name. 
.br
 Function was successful. 
.PP
NULL 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lserrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
$LSF_CONFDIR/lsf.shared 
.br
$LSF_CONFDIR/lsf.cluster.cluster_name
.PP
.SH "See also:"
\fBls_info\fP 
.PP
\fBls_getclustername\fP 
.PP
\fBls_getmodelfactor\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
