.TH "ls_rlseek" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls_rlseek \- ls_rlseek 
Performs a seek operation on a file on a remote host.
.PP
This routine performs operations on files located on remote hosts. This call corresponds to the UNIX lseek() system calls.
.PP
\fBls_rlseek\fP performs a read operation on an opened file that is referenced by rfd. The file has been previously opened using \fBls_ropen\fP.
.PP
Either the RES must be running at the remote host to service any remote file operation or rcp() be available.
.PP
\fBls_initrex\fP must be called before calling any remote file operation.
.PP
This remote file operation makes use of a Remote File Server on the remote host. When this RFS shuts down, its status will be reported to its client. The client should ignore this status.
.PP
\fB #include <sys/types.h> 
.br
 #include <unistd.h> 
.br
 #include <sys/stat.h> 
.br
 #include <fcntl.h> 
.br
 #include <limits.h> 
.br
 #include <lsf/lsf.h>\fP
.PP
\fB off_t ls_rlseek(int rfd, off_t offset, int whence) \fP
.PP
.SH "Parameters:"
\fIrfd\fP References the file that is to be sought. 
.br
\fIoffset\fP Offset of the file. 
.br
\fIwhence\fP Whence.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int: 0 
.br
 Response is the same from its UNIX counterpart. 
.PP
int:-1 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lserrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
none
.PP
.SH "See also:"
\fBls_ropen\fP 
.PP
\fBls_rread\fP 
.PP
\fBls_rwrite\fP 
.PP
\fBls_rclose\fP 
.PP
\fBls_rstat\fP 
.PP
\fBls_rfstat\fP 
.PP
\fBls_rgetmnthost\fP 
.PP
\fBls_rfcontrol\fP 
.PP
\fBls_initrex\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
