.TH "ls_rkill" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls_rkill \- ls_rkill 
Signals a remote task
.PP
\fBls_rkill\fP sends the signal sig to the remote task tid and all its children that belong to the same UNIX process group. tid is the remote task ID that is returned by \fBls_rtask\fP or \fBls_rtaske\fP. If sig is zero, then this call only polls the existence of the remote task tid.
.PP
Any program using this routine must call \fBls_initrex\fP first.
.PP
Any program using this API must be setuid to root if LSF_AUTH is not defined in the lsf.conf file.
.PP
\fB #include <lsf/lsf.h> 
.br
 #include <signal.h>\fP
.PP
\fB int ls_rkill(int tid, int sig) \fP
.PP
.SH "Parameters:"
\fIsig\fP The signal sent to the tid. 
.br
\fItid\fP The remote task ID returned by \fBls_rtask\fP or \fBls_rtaske\fP.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int:0 
.br
 Function was successful. 
.PP
int:-1 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lserrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf
.PP
.SH "See also:"
\fBls_rtask\fP 
.PP
\fBls_rtaske\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
