.TH "ls_rfterminate" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls_rfterminate \- ls_rfterminate 
Closes connection to the RES's file server process.
.PP
\fB #include <sys/types.h> 
.br
 #include <unistd.h> 
.br
 #include <sys/stat.h> 
.br
 #include <fcntl.h> 
.br
 #include <limits.h> 
.br
 #include <lsf/lsf.h>\fP
.PP
\fB int ls_rfterminate(char *host) \fP
.PP
.SH "Parameters:"
\fI*host\fP The host names.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int:0 
.br
 The function was successful.
.PP
int:-1 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lserrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
none
.PP
.SH "See also:"
\fBls_ropen\fP 
.PP
\fBls_rread\fP 
.PP
\fBls_rwrite\fP 
.PP
\fBls_rlseek\fP 
.PP
\fBls_rclose\fP 
.PP
\fBls_rstat\fP 
.PP
\fBls_rfstat\fP 
.PP
\fBls_rgetmnthost\fP 
.PP
\fBls_initrex\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
