.TH "ls_sysmsg" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls_sysmsg \- ls_sysmsg 
Obtains LSF error messages.
.PP
\fBls_sysmsg\fP is a LSLIB library routine for obtaining LSF error messages. The global variable lserrno, maintained by LSLIB, indicates the error number of the most recent LSLIB call that caused an error.
.PP
\fBls_sysmsg\fP returns a character string that contains an error message that corresponds to the current value of lserrno. If an LSLIB call failed due to a system call, then the system error message as indicated by errno is included in the error message.
.PP
\fB#include <lsf/lsf.h> 
.br
 char *ls_sysmsg(void)\fP
.PP
.SH "Parameters:"
\fInone\fP 
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
char *:Return Load Sharing System error message defined by lserrno. 
.br
 Function was successful. 
.PP
NULL 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
Systems that conform to the Single UNIX specification are not required to detect error conditions for this function.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
lsf/lsf.h
.PP
.SH "See also:"
\fBls_perror\fP 
.PP
\fBls_errlog\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
