.TH "ls_unlockhost" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ls_unlockhost \- ls_unlockhost 
Unlocks a locked local host.
.PP
\fBls_unlockhost\fP unlocks a host locked by \fBls_lockhost\fP. On success, \fBls_unlockhost\fP changes the status of the local host to indicate that it is no longer locked by the user.
.PP
Any program using this API must be setuid to root if LSF_AUTH is not defined in the lsf.conf file.
.PP
\fB#include <lsf/lsf.h> 
.br
 int ls_unlockhost(void)\fP
.PP
.SH "Parameters:"
\fInone\fP 
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int:0 
.br
 The function was successful. 
.PP
int:-1 
.br
 The function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lserrno is set to indicate the error. In particular, \fBls_unlockhost\fP sets lserrno to LSE_LIM_NLOCKED if the host is not locked.
.PP
.SH "Equivalent line commands:" 
.PP
lsadmin limunlock
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf 
.br
$LSF_CONFDIR/lsf.shared 
.br
$LSF_CONFDIR/lsf.cluster.cluster_name
.PP
.SH "See also:"
\fBls_limcontrol\fP 
.PP
\fBls_lockhost\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
