.TH "lsb_openjobinfo_a_ext" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_openjobinfo_a_ext \- lsb_openjobinfo_a_ext 
Returns the name and number of jobs and hosts in the master batch daemon with additional host group information.
.PP
\fBlsb_openjobinfo_a_ext\fP is run from \fBlsb_openjobinfo_a\fP using the same parameters and provides the same information as \fBlsb_openjobinfo_a\fP, but with additional host group information.
.PP
\fBlsb_openjobinfo_a_ext\fP passes information about jobs based on the value of jobId, jobName, userName, queueName, or hostName. Only one parameter can be chosen. The other parameters must be NULL or 0.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB struct \fBjobInfoHeadExt\fP * lsb_openjobinfo_a_ext (LS_LONG_INT jobId, char *jobName, char *userName, char *queueName, char *hostName, int options)\fP
.PP
.SH "Parameters:"
\fIjobId\fP Passes information about jobs with the given job ID. If jobId is 0, \fBlsb_openjobinfo_a_ext\fP looks to another parameter to return information about jobs. If information about a member of a job array is to be passed, use the array form jobID[ i ] where jobID is the job array name, and i is the index value. 
.br
\fI*jobName\fP Passes information about jobs with the given job name. If jobName is NULL, \fBlsb_openjobinfo_a_ext\fP looks to another parameter to return information about jobs. 
.br
\fI*userName\fP Passes information about jobs submitted by the named user or user group, or by all users if userName is all. If userName is NULL, \fBlsb_openjobinfo_a_ext\fP assumes the user is invoking this call. 
.br
\fI*queueName\fP Passes information about jobs belonging to the named queue. If queueName is NULL, jobs in all queues of the batch system will be considered. 
.br
\fI*hostName\fP Passes information about jobs on the named host, host group or cluster name. If hostName is NULL, jobs on all hosts of the batch system will be considered. 
.br
\fIoptions\fP <lsf/lsbatch.h> defines the flags shown in def_lsb_openjobinfo_a constructed from bits. Use the bitwise OR to set more than one flag.
.PP
.SH "Data Structures:" 
.PP
\fBjobInfoHeadExt\fP
.PP
.SH "Define Statements:" 
.PP
\fBdefs_lsb_openjobinfo_a\fP
.PP
.SH "Returns:"
struct \fBjobInfoHeadExt\fP * 
.br
 On success, returns an array of data type struct \fBjobInfoHeadExt\fP *, which represents the name and number of jobs and hosts in the master batch daemon with the host group information. 
.PP
NULL 
.br
 The function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line command:" 
.PP
bjobs
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf 
.br
 $LSB_CONFDIR/cluster_name/configdir/lsb.params
.PP
.SH "See also:"
\fBlsb_openjobinfo\fP 
.PP
\fBlsb_closejobinfo\fP 
.PP
\fBlsb_readjobinfo\fP 
.PP
\fBlsb_readframejob\fP 
.PP

.ad l
.nh
.SH NAME
jobInfoHeadExt \- job Information head extent  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBjobInfoHead\fP * \fBjobInfoHead\fP"
.br
.ti -1c
.RI "struct groupInfoReply * \fBgroupInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
job Information head extent 
.SH "Field Documentation"
.PP 
.SS "struct \fBjobInfoHead\fP* \fBjobInfoHeadExt::jobInfoHead\fP"
.PP
Job Information header. 
.PP
.SS "struct groupInfoReply* \fBjobInfoHeadExt::groupInfo\fP"
.PP
Group Information returned. 
.PP


.ad l
.nh
.SH NAME
defs_lsb_openjobinfo_a \- defs_lsb_openjobinfo_a is part of defs_lsb_openjobinfo  

.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBALL_JOB\fP   0x0001"
.br
.ti -1c
.RI "#define \fBDONE_JOB\fP   0x0002"
.br
.ti -1c
.RI "#define \fBPEND_JOB\fP   0x0004"
.br
.ti -1c
.RI "#define \fBSUSP_JOB\fP   0x0008"
.br
.ti -1c
.RI "#define \fBCUR_JOB\fP   0x0010"
.br
.ti -1c
.RI "#define \fBLAST_JOB\fP   0x0020"
.br
.in -1c
.SH "Detailed Description"
.PP 
defs_lsb_openjobinfo_a is part of defs_lsb_openjobinfo 
.SH "Define Documentation"
.PP 
.SS "#define ALL_JOB   0x0001"
.PP
Information about all jobs, including unfinished jobs (pending, running or suspended) and recently finished jobs. 
.PP
LSF remembers jobs finished within the preceding period. This period is set by the parameter CLEAN_PERIOD in the lsb.params file. The default is 3600 seconds (1 hour). (See lsb.params). The command line equivalent is bjobs -a. 
.SS "#define DONE_JOB   0x0002"
.PP
Information about recently finished jobs. 
.PP

.SS "#define PEND_JOB   0x0004"
.PP
Information about pending jobs. 
.PP

.SS "#define SUSP_JOB   0x0008"
.PP
Information about suspended jobs. 
.PP

.SS "#define CUR_JOB   0x0010"
.PP
Information about all unfinished jobs. 
.PP

.SS "#define LAST_JOB   0x0020"
.PP
Information about the last submitted job. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
