.TH "lsb_reconfig" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_reconfig \- lsb_reconfig 
Dynamically reconfigures an LSF batch system.
.PP
\fBlsb_reconfig\fP dynamically reconfigures an LSF batch system to pick up new configuration parameters and changes to the job queue setup since system startup or the last reconfiguration (see lsb.queues).
.PP
To restart a slave batch daemon, use \fBlsb_hostcontrol\fP. This call is successfully invoked only by root or by the LSF administrator.
.PP
Any program using this API must be setuid to root if LSF_AUTH is not defined in the lsf.conf file.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_reconfig (struct \fBmbdCtrlReq\fP *req)\fP
.PP
.SH "Parameters:"
\fI*req\fP mbatchd control request.
.PP
.SH "Data Structures:" 
.PP
\fBmbdCtrlReq\fP
.PP
.SH "Define Statements:" 
.PP
\fBmbd_operation\fP
.PP
.SH "Returns:"
int:0 
.br
 Function was successful. 
.PP
int:-1 
.br
 The function failed.
.PP
.SH "Errors:" 
.PP
On failure, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
badmin reconfig
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf
.PP
.SH "See also:"
\fBlsb_openjobinfo\fP 
.PP

.ad l
.nh
.SH NAME
mbdCtrlReq \- mbatchd control request.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBopCode\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
mbatchd control request. 
.SH "Field Documentation"
.PP 
.SS "int \fBmbdCtrlReq::opCode\fP"
.PP
Operation applied, defined in \fBmbd_operation\fP. 
.PP
.SS "char* \fBmbdCtrlReq::name\fP"
.PP
Not used so far. 
.PP
.SS "char* \fBmbdCtrlReq::message\fP"
.PP
The message attached by the admin. 
.PP


.ad l
.nh
.SH NAME
mbd_operation \- options for \fBlsb_reconfig\fP call  

.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMBD_RESTART\fP   0"
.br
.ti -1c
.RI "#define \fBMBD_RECONFIG\fP   1"
.br
.ti -1c
.RI "#define \fBMBD_CKCONFIG\fP   2"
.br
.in -1c
.SH "Detailed Description"
.PP 
options for \fBlsb_reconfig\fP call 
.SH "Define Documentation"
.PP 
.SS "#define MBD_RESTART   0"
.PP
mbatchd restart 
.PP
.SS "#define MBD_RECONFIG   1"
.PP
mbatchd reread configuration files 
.PP
.SS "#define MBD_CKCONFIG   2"
.PP
mbatchd check validity of configuration files 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
