.TH "lsb_closejobinfo" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_closejobinfo \- lsb_closejobinfo 
Closes job information connection with the master batch daemon.
.PP
Use \fBlsb_closejobinfo\fP to close the connection to the master batch daemon after opening a job information connection with \fBlsb_openjobinfo\fP and reading job records with \fBlsb_readjobinfo\fP.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB void lsb_closejobinfo(void)\fP
.PP
.SH "Parameters:"
\fIvoid\fP 
.br
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
void 
.br
 There's no returns value.
.PP
.SH "Errors:" 
.PP
On failure, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
${LSF_ENVDIR:-/etc}/lsf.conf
.PP
.SH "See also:"
\fBlsb_openjobinfo\fP 
.PP
\fBlsb_openjobinfo_a\fP 
.PP
\fBlsb_readjobinfo\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
