.TH "lsb_streamversion" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_streamversion \- lsb_streamversion 
Version of the current event type supported by mbatchd.
.PP
\fBlsb_streamversion\fP returns the event version number of mbatchd, which is the version of the events to be written to the stream file. This API function is inside liblsbstream.so.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB char * lsb_streamversion(void)\fP
.PP
.SH "Parameters:"
\fIvoid\fP 
.br
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
char *:Pointer to a string of the current event version in mbatchd, also known as THIS_VERSION. 
.br
 Function was successful. 
.PP
NULL 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
$LSB_CONFDIR/cluster_name/configdir/lsb.params
.PP
.SH "See also:"
\fBlsb_closestream\fP 
.PP
\fBlsb_geteventrec\fP 
.PP
\fBlsb_openstream\fP 
.PP
\fBlsb_puteventrec\fP 
.PP
\fBlsb_readstreamline\fP 
.PP
\fBlsb_writestream\fP 
.PP
\fBlsb_readstream\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
