.TH "lsb_resize_cancel" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_resize_cancel \- lsb_resize_cancel 
Cancels a pending job resize allocation request.
.PP
Use \fBlsb_resize_cancel\fP to cancel a pending allocation request for a resizable job. A running job can only have one pending request at any particular time. If one request is still pending, additional requests are rejected with a proper error code.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_resize_cancel(LS_LONG_INT jobId);\fP
.PP
.SH "Parameters:"
\fIjobId\fP LSF job ID
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int:0 
.br
 On success, returns zero. 
.PP
int:-1 
.br
 On failure, returns -1.
.PP
.SH "Errors:" 
.PP
lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
bresize cancel job_ID
.PP
.SH "Files:" 
.PP
none
.PP
.SH "See also:"
\fBlsb_resize_release\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
