.TH "lsb_forcekilljob" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_forcekilljob \- lsb_forcekilljob 
This function is used to send special force kill signal.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB int lsb_forcekilljob(LS_LONG_INT jobId)\fP
.PP
.SH "Parameters:"
\fIjobId\fP which job is to be killed.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
int:0 
.br
 Function was successful. 
.PP
int:-1 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
On failure, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
none
.PP
.SH "See also:"
\fBlsb_signaljob\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
