.TH "lsb_sysmsg" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_sysmsg \- lsb_sysmsg 
Returns a pointer to static data.
.PP
\fBlsb_sysmsg\fP returns a pointer to static data which stores the batch error message corresponding to lsberrno. The global variable lsberrno maintained by LSBLIB holds the error number from the most recent LSBLIB call that caused an error. If lsberrno == LSBE_SYS_CALL, then the system error message defined by errno is also returned. If lsberrno == LSBE_LSLIB, then the error message returned by \fBls_sysmsg\fP is returned.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB char *lsb_sysmsg (void)\fP
.PP
.SH "Parameters:"
\fIvoid\fP 
.br
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
char *:Return LSBATCH error message defined by lsberrno. 
.br
 If lsberrno == LSBE_SYS_CALL, then the system error message defined by errno is also returned. 
.br
 If lsberrno == LSBE_LSLIB, then the error message returned by \fBls_sysmsg\fP is returned. 
.PP
NULL 
.br
 Function failed.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line commands:" 
.PP
none
.PP
.SH "Files:" 
.PP
none
.PP
.SH "See also:"
\fBls_perror\fP 
.PP
\fBls_sysmsg\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
