.TH "lsb_perror" 3 "3 Sep 2009" "Version 7.0" "Platform LSF 7.0.6 C API Reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsb_perror \- lsb_perror 
Prints a batch LSF error message on stderr.
.PP
\fBlsb_perror\fP prints a batch LSF error message on stderr. The usrMsg is printed out first, followed by a ':' and the batch error message corresponding to lsberrno.
.PP
\fBlsb_perror\fP - Print LSBATCH error message on stderr. In addition to the error message defined by lsberrno, user supplied message usrMsg1 is printed out first and a ':' is added to separate * usrMsg1 and LSBATCH error message.
.PP
\fB#include <lsf/lsbatch.h>\fP
.PP
\fB void lsb_perror (char *usrMsg)\fP
.PP
.SH "Parameters:"
\fI*usrMsg\fP A user supplied error message.
.PP
.SH "Data Structures:" 
.PP
none
.PP
.SH "Define Statements:" 
.PP
none
.PP
.SH "Returns:"
void 
.br
 Prints out the user supplied error message.
.PP
.SH "Errors:" 
.PP
If the function fails, lsberrno is set to indicate the error.
.PP
.SH "Equivalent line command:" 
.PP
none
.PP
.SH "Files:" 
.PP
none
.PP
.SH "See also:"
none 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform LSF 7.0.6 C API Reference from the source code.
