#!/bin/bash

# From http://www.bioinformatics.babraham.ac.uk/projects/bismark/Bismark_User_Guide_v0.15.0.pdf
# Test fastq from http://www.bioinformatics.babraham.ac.uk/projects/download.html#bismark
# Test fasta from hg19

set -e

# Requires samtools 1.2 or higher so must load the module
module load samtools/1.3

[ -d testdata/Bisulfite_Genome/ ] && rm -rf testdata/Bisulfite_Genome/

# Defaults to bowtie2 so have to specify bowtie1 if you want it
bismark_genome_preparation --bowtie1 testdata/
bismark --bowtie1 -n 1 -l 50 testdata/ test_data.fastq
# Now outputs bam format
bismark_methylation_extractor -s --comprehensive test_data.fastq_bismark.bam

[ -d testdata/Bisulfite_Genome/ ] && rm -rf testdata/Bisulfite_Genome/
rm -rf *.txt
rm -rf *.png
rm -f test_data.fastq_bismark.bam
