Name:		vcftools
Version:	0.1.15
Release:	1%{?dist}
Summary:	VCF file manipulation tools

Group:		Applications/Engineering
License:	GPLv3 
URL:		https://vcftools.github.io/index.html
Source0:	https://github.com/vcftools/vcftools/releases/download/v%{version}/%{name}-%{version}.tar.gz
Requires:	tabix
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:	zlib-devel
#BuildRequires:	zlib-devel,autogen,automake,autoconf


%description
A program package designed for working with VCF files, such as those
generated by the 1000 Genomes Project. The aim of VCFtools is to
provide methods for working with VCF files: validating, merging,
comparing and calculate some basic population genetic statistics
.
%prep
%setup -q -n %{name}-%{version}
#%patch0 -p1

%build
#./autogen.sh
./configure --prefix="%{buildroot}/usr"
make %{?_smp_mflags} CPPFLAGS="%{optflags}"

%install
rm -rf %{buildroot}
make install PREFIX="%{buildroot}/usr" MODDIR="%{buildroot}%{perl_vendorarch}" \
BINDIR="%{buildroot}%{_bindir}" MANDIR="%{buildroot}%{_mandir}/man1"
mkdir -p %{buildroot}%{_mandir}/man1

#install -m 0775 %{_builddir}/%{name}-%{version}/src/cpp/vcftools %{buildroot}%{_bindir}
#install -m 0644 %{_builddir}/%{name}-%{version}/src/cpp/vcftools.1 %{buildroot}%{_mandir}/man1


%clean
rm -rf %{buildroot}


%files
%defattr(-,root,root,-)
#%doc README.txt 
/usr/bin/fill-aa
/usr/bin/fill-an-ac
/usr/bin/fill-fs
/usr/bin/fill-ref-md5
/usr/bin/vcf-annotate
/usr/bin/vcf-compare
/usr/bin/vcf-concat
/usr/bin/vcf-consensus
/usr/bin/vcf-contrast
/usr/bin/vcf-convert
/usr/bin/vcf-fix-newlines
/usr/bin/vcf-fix-ploidy
/usr/bin/vcf-indel-stats
/usr/bin/vcf-isec
/usr/bin/vcf-merge
/usr/bin/vcf-phased-join
/usr/bin/vcf-query
/usr/bin/vcf-shuffle-cols
/usr/bin/vcf-sort
/usr/bin/vcf-stats
/usr/bin/vcf-subset
/usr/bin/vcf-to-tab
/usr/bin/vcf-tstv
/usr/bin/vcf-validator
/usr/bin/vcftools
/usr/share/man/man1/vcftools.1.gz
/usr/share/perl5/FaSlice.pm
/usr/share/perl5/Vcf.pm
/usr/share/perl5/VcfStats.pm

#%{_mandir}/man1/vcftools.1*
#%{_bindir}/vcf-compare
#%{_bindir}/fill-aa
#%{_bindir}/fill-an-ac
#%{_bindir}/vcf-merge
#%{_bindir}/vcf-query
#%{_bindir}/vcf-annotate
#%{_bindir}/vcf-concat
#%{_bindir}/vcf-convert
#%{_bindir}/vcf-isec
#%{_bindir}/vcf-sort
#%{_bindir}/vcf-stats
#%{_bindir}/vcf-subset
#%{_bindir}/vcf-to-tab
#%{_bindir}/vcf-validator
#%{_bindir}/fill-fs
#%{_bindir}/fill-ref-md5
#%{_bindir}/vcf-consensus
#%{_bindir}/vcf-contrast
#%{_bindir}/vcf-fix-ploidy
#%{_bindir}/vcf-indel-stats
#%{_bindir}/vcf-phased-join
#%{_bindir}/vcf-shuffle-cols
#%{_bindir}/vcf-tstv

#%attr(0755, root, root) %{_bindir}/vcftools
#%{perl_vendorarch}/FaSlice.pm
#%{perl_vendorarch}/Vcf.pm
#%{perl_vendorarch}/VcfStats.pm

%changelog
* Wed Apr 19 2017 Shane Sturrock <shane.sturrock@nzgenomics.co.nz> - 0.1.15-1
- Minor release to include recent small code changes.
- Output in LDhelmet format
- Minor bug fixes.

* Mon Feb 27 2016 Shane Sturrock <shane.sturrock@nzgenomics.co.nz> - 0.1.14-1
- Compiling and building vcftools is now done by autotools (see README for
  installation instructions)
- Changed temporary file handling (from mktemp to mkstemp)
- Minor bug fixes

* Tue Aug 04 2015 Shane Sturrock <shane@biomatters.com> - 0.1.13-1
- Migration of the vcftools project (and website) from sourceforge to github
- Optimizations for reading and writing BCF files
- Edits to code for C++ 11 compatibility
- Added --mendel option for finding Mendelian errors in trios
- Allow --diff options to output to stream by splitting up function into
  --diff-site and --diff-indv options
- Added experimental --hapcount function to determine the amount of unique
  haplotypes in user defined bins
- Addition of "any" options to filter by frequency or count of any
  alternate allele (instead of requiring all of them to pass)
- Improvements to temporary file handling for all LD functions
- Added --chrom-map option to allow user specified chromosomes for writing
  out plink files
- Allow site filtering with multiple keep and exclude files
- Tajima's D now reports NaN in the absence of data
- Various bug fixes

* Mon Dec 08 2014 Shane Sturrock <shane@biomatters.com> - 0.1.12b-1
- Diff functions no longer write to temporary files, but instead scan through 
  both files simultaneously. Files must be sorted in the same chromosomal 
  order.
- All linkage disequilibrium functions now write fewer and smaller temporary 
  files.
- Added an option to allow user to specify the location of temporary files.
- Regular diff function now reports if a site from one file overlaps with a 
  site from the other file.
- Switch error diff function now reports a range of bases where the switch 
  may have occurred.
- Bug fix for long run of homozygosity function.
- Added filters --positions-overlap and --exclude-positions-overlap to filter 
  out any sites that overlap any positions in a given file.
- Added the --contigs parameter for declaring contigs not found in the header 
  for vcf to bcf conversion.

* Mon Mar 10 2014 Shane Sturrock <shane@biomatters.com> - 1.12-1
- Added options:
  --stdout, -c : These options force the program to write to standard out
  instead of directly to file
  --relatedness2 : Calculate and output a relatedness statistic based on the
  method of Manichaikul et al., Bioinformatics 2010

- Removed options:
  --min-indv-meanDP <float>
  --max-indv-mean-DP <float>
  --mind <float>
  --recode-to-stream (functionality replaced by --recode used with --stdout)
  --recode-bcf-to-stream (functionality replaced by --recode-bcf used with
  --stdout)
  --force-write-index

- Changed options:
  --vcf, --gzvcf, --bcf : These options now can accept a dash character "-"
  instead of a filename, allowing the program to read from standard input.
  --phased : Now this function only removes sites with unphased genotypes and
  does not remove individuals with all unphased genotypes.
  --missing : This function has been split into two separate functions that
  provides the same functionality as the previously: --missing-indv and
  --missing-site
  --filtered-sites : This function has been split into two separate functions
  that provides the same functionality as the previously: --kept-sites and
  --removed-sites
  --TsTv <int> : This function no longer outputs a summary along with the
  TsTv bin file. To output only the summary file, use function: --TsTv-summary
  --geno <float> : This option has been renamed --max-missing <float> but
  keeps the same functionality.

* Wed Jun 26 2013 Shane Sturrock <shane@biomatters.com> - 1.11-1
- New upstream release

* Wed Dec 05 2012 Carl Jones <carl@biomatters.com> - 1.10-1
- New upstream release

* Tue Sep 04 2012 Carl Jones <carl@biomatters.com> - 0.1.9-2
- Add dependancy on tabix
* Sun Jul 29 2012  <bloch@verdurin.com> - 0.1.9-1
- Update to 0.1.9
- Remove perl patch that's no longer needed

* Thu Jan  5 2012 Adam Huffman <verdurin@fedoraproject.org> - 0.1.7-1
- update to upstream release 0.1.7
- remove fill-rsIDs
- update Perl makefile patch

* Sun Jul 31 2011 Adam Huffman <bloch@verdurin.com> - 0.1.6-1
- update to 0.1.6

* Tue May  3 2011 Adam Huffman <bloch@verdurin.com> - 0.1.5-2
- minor fix to Jack's Perl patch
- permissions fix
- hardcoded path fix
- cleaner Makefile fix

* Sun May 1 2011 Jack Tanner <ihok@hotmail.com> - 0.1.5-1
- bump to 0.1.5
- rename compare-vcf, merge-vcf, and query-vcf to vcf-compare,
  vcf-merge, and vcf-query
- add VcfStats.pm to perl export
- patch perl/Makefile to export VcfStats.pm

* Mon Mar 21 2011 Adam Huffman <bloch@verdurin.com> - 0.1.4a-1
- initial version
- fix CPPFLAGS
- fix hardcoded installation location

