Name:		vcftools
Version:	0.1.12b
Release:	1%{?dist}
Summary:	VCF file manipulation tools

Group:		Applications/Engineering
License:	GPLv3 
URL:		http://vcftools.sourceforge.net/
Source0:	http://downloads.sourceforge.net/%{name}/%{name}_%{version}.tar.gz
Requires:	tabix

BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:	zlib-devel


%description
A program package designed for working with VCF files, such as those
generated by the 1000 Genomes Project. The aim of VCFtools is to
provide methods for working with VCF files: validating, merging,
comparing and calculate some basic population genetic statistics
.
%prep
%setup -q -n %{name}_%{version}
#%patch0 -p1

%build
make %{?_smp_mflags} CPPFLAGS="%{optflags}"


%install
rm -rf %{buildroot}
make install PREFIX=%{buildroot}/usr MODDIR="%{buildroot}/%{perl_vendorarch}" \
BINDIR="%{buildroot}/%{_bindir}"

install -m 0775 %{_builddir}/%{name}_%{version}/cpp/vcftools %{buildroot}/%{_bindir}


%clean
rm -rf %{buildroot}


%files
%defattr(-,root,root,-)
%doc README.txt
%{_bindir}/vcf-compare
%{_bindir}/fill-aa
%{_bindir}/fill-an-ac
#%%{_bindir}/fill-rsIDs
%{_bindir}/vcf-merge
%{_bindir}/vcf-query
%{_bindir}/vcf-annotate
%{_bindir}/vcf-concat
%{_bindir}/vcf-convert
%{_bindir}/vcf-isec
%{_bindir}/vcf-sort
%{_bindir}/vcf-stats
%{_bindir}/vcf-subset
%{_bindir}/vcf-to-tab
%{_bindir}/vcf-validator
%{_bindir}/fill-fs
%{_bindir}/fill-ref-md5
%{_bindir}/vcf-consensus
%{_bindir}/vcf-contrast
%{_bindir}/vcf-fix-ploidy
%{_bindir}/vcf-indel-stats
%{_bindir}/vcf-phased-join
%{_bindir}/vcf-shuffle-cols
%{_bindir}/vcf-tstv

%attr(0755, root, root) %{_bindir}/vcftools
%{perl_vendorarch}/FaSlice.pm
%{perl_vendorarch}/Vcf.pm
%{perl_vendorarch}/VcfStats.pm

%changelog
* Mon Dec 08 2014 Shane Sturrock <shane@biomatters.com> - 0.1.12b-1
- Diff functions no longer write to temporary files, but instead scan through 
  both files simultaneously. Files must be sorted in the same chromosomal 
  order.
- All linkage disequilibrium functions now write fewer and smaller temporary 
  files.
- Added an option to allow user to specify the location of temporary files.
- Regular diff function now reports if a site from one file overlaps with a 
  site from the other file.
- Switch error diff function now reports a range of bases where the switch 
  may have occurred.
- Bug fix for long run of homozygosity function.
- Added filters --positions-overlap and --exclude-positions-overlap to filter 
  out any sites that overlap any positions in a given file.
- Added the --contigs parameter for declaring contigs not found in the header 
  for vcf to bcf conversion.

* Mon Mar 10 2014 Shane Sturrock <shane@biomatters.com> - 1.12-1
- Added options:
  --stdout, -c : These options force the program to write to standard out
  instead of directly to file
  --relatedness2 : Calculate and output a relatedness statistic based on the
  method of Manichaikul et al., Bioinformatics 2010

- Removed options:
  --min-indv-meanDP <float>
  --max-indv-mean-DP <float>
  --mind <float>
  --recode-to-stream (functionality replaced by --recode used with --stdout)
  --recode-bcf-to-stream (functionality replaced by --recode-bcf used with
  --stdout)
  --force-write-index

- Changed options:
  --vcf, --gzvcf, --bcf : These options now can accept a dash character "-"
  instead of a filename, allowing the program to read from standard input.
  --phased : Now this function only removes sites with unphased genotypes and
  does not remove individuals with all unphased genotypes.
  --missing : This function has been split into two separate functions that
  provides the same functionality as the previously: --missing-indv and
  --missing-site
  --filtered-sites : This function has been split into two separate functions
  that provides the same functionality as the previously: --kept-sites and
  --removed-sites
  --TsTv <int> : This function no longer outputs a summary along with the
  TsTv bin file. To output only the summary file, use function: --TsTv-summary
  --geno <float> : This option has been renamed --max-missing <float> but
  keeps the same functionality.

* Wed Jun 26 2013 Shane Sturrock <shane@biomatters.com> - 1.11-1
- New upstream release

* Wed Dec 05 2012 Carl Jones <carl@biomatters.com> - 1.10-1
- New upstream release

* Tue Sep 04 2012 Carl Jones <carl@biomatters.com> - 0.1.9-2
- Add dependancy on tabix
* Sun Jul 29 2012  <bloch@verdurin.com> - 0.1.9-1
- Update to 0.1.9
- Remove perl patch that's no longer needed

* Thu Jan  5 2012 Adam Huffman <verdurin@fedoraproject.org> - 0.1.7-1
- update to upstream release 0.1.7
- remove fill-rsIDs
- update Perl makefile patch

* Sun Jul 31 2011 Adam Huffman <bloch@verdurin.com> - 0.1.6-1
- update to 0.1.6

* Tue May  3 2011 Adam Huffman <bloch@verdurin.com> - 0.1.5-2
- minor fix to Jack's Perl patch
- permissions fix
- hardcoded path fix
- cleaner Makefile fix

* Sun May 1 2011 Jack Tanner <ihok@hotmail.com> - 0.1.5-1
- bump to 0.1.5
- rename compare-vcf, merge-vcf, and query-vcf to vcf-compare,
  vcf-merge, and vcf-query
- add VcfStats.pm to perl export
- patch perl/Makefile to export VcfStats.pm

* Mon Mar 21 2011 Adam Huffman <bloch@verdurin.com> - 0.1.4a-1
- initial version
- fix CPPFLAGS
- fix hardcoded installation location

