--- Makefile.orig	2014-04-16 13:12:50.220267246 +1200
+++ Makefile	2014-04-16 13:14:21.504818185 +1200
@@ -27,7 +27,7 @@
 	cd Chrysalis && $(MAKE) UNSUPPORTED=yes $(CHRYSALIS_MAKE_FLAGS)
 
 jellyfish:
-	cd trinity-plugins/jellyfish && ./configure CC=gcc CXX=g++ --prefix=`pwd` && $(MAKE) AM_CPPFLAGS="-Wall -Wnon-virtual-dtor -I"`pwd`
+	cd trinity-plugins/jellyfish && ./configure --enable-all-static CC=gcc CXX=g++ --prefix=`pwd` && $(MAKE) AM_CPPFLAGS="-Wall -Wnon-virtual-dtor -I"`pwd`
 
 fastool:
 	cd trinity-plugins/fastool && $(MAKE)
