
.ad l

.ll 72

.TH bparams 1 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBbparams\fR
.sp 2
   displays information about configurable system parameters in
   \fRlsb.params\fR
.sp 2

.sp 2 .SH "Synopsis"
\fBSynopsis\fR
.sp 2
bparams [-a] [-l]
.sp 2
bparams [-h | -V]
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Displays the following parameter values:
.sp 2
     o  
         Default Queues
.sp 2
     o  
         Job Dispatch Interval
.sp 2
     o  
         Job Checking Interval
.sp 2
     o  
         Job Accepting Interval
.sp 2 .SH "Options"
\fBOptions\fR
.sp 2
   \fB-a\fR
.br
               All format. Displays all the configurable
               parameters set in lsb.params.
.sp 2
   \fB-l\fR
.br
               Long format. Displays detailed information about
               all the configurable parameters in lsb.params.
.sp 2
   \fB-h\fR
.br
               Prints command usage to stderr and exits.
.sp 2
   \fB-V\fR
.br
               Prints LSF release version to stderr and exits.
.sp 2 .SH "See also"
\fBSee also\fR
.sp 2
   \fR\fRlsb.params
