
.ad l

.ll 72

.TH bresources 1 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBbresources\fR
.sp 2
   displays information about resource reservation and resource
   limits configuration
.sp 2

.sp 2 .SH "Synopsis"
\fBSynopsis\fR
.sp 2
bresources [-s] [resource_name ...]
.sp 2
bresources [-h | -V]
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   By default, bresources displays all resource configurations in
   lsb.resources. This is the same as blimits -c.
.sp 2 .SH "Options"
\fBOptions\fR
.sp 2
   \fB-s\fR
.br
               Displays per-resource reservation configurations
               from the ReservationUsage section of
               lsb.resources. For example:
.sp 2
               bresources -sBegin ReservationUsageRESOURCE            METHOD    RESERVElicense1            PER_HOST     Ylicense2            PER_SLOT     Ylicense3            PER_JOB      Nlicense5            PER_HOST     Ylicense6            PER_JOB      YEnd ReservationUsage
.sp 2
   \fB\fIresource_name\fB ...\fR
.br
               Only displays information about the specified
               resource. For example:
.sp 2
               bresources -s  license1RESOURCE            METHOD    RESERVElicense1            PER_HOST     Y
.sp 2
   \fB-h\fR
.br
               Prints command usage to stderr and exits.
.sp 2
   \fB-V\fR
.br
               Prints LSF release version to stderr and exits.
.sp 2
