
.ad l

.ll 72

.TH lsfmon 1 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBlsfmon\fR
.sp 2
   installs or uninstalls LSF Monitor
.sp 2

.sp 2 .SH "Synopsis"
\fBSynopsis\fR
.sp 2
lsfmon -install
.sp 2
lsfmon -remove
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Installs or uninstalls LSF Monitor in an existing cluster.
.sp 2
   LSF Monitor runs on Microsoft Windows and allows you to use
   Windows Performance Monitor to chart information about the LSF
   cluster.
.sp 2
   The LSF Monitor service runs under the account of an LSF
   cluster administrator.
.sp 2 .SH "Options"
\fBOptions\fR
.sp 2
   \fB-install \fR
.br
               Installs LSF Monitor on the host.
.sp 2
   \fB-remove\fR
.br
               Removes LSF Monitor from the host.
