
.ad l

.ll 72

.TH lsb.events 5 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBlsb.events\fR
.sp 2
   The LSF batch event log file lsb.events is used to display LSF
   batch event history and for mbatchd failure recovery.
.sp 2
   Whenever a host, job, or queue changes status, a record is
   appended to the event log file. The file is located in
   LSB_SHAREDIR/\fIcluster_name\fR/logdir, where LSB_SHAREDIR
   must be defined in lsf.conf(5) and \fIcluster_name\fR is the
   name of the LSF cluster, as returned by lsid. See mbatchd(8)
   for the description of LSB_SHAREDIR.
.sp 2
   The bhist command searches the most current lsb.events file
   for its output.
.sp 2
\fBlsb.events structure\fR
.sp 2
   The event log file is an ASCII file with one record per line.
   For the lsb.events file, the first line has the format \fR#
   \fIhistory_seek_position\fR>\fR, which indicates the file
   position of the first history event after log switch. For the
   lsb.events.# file, the first line has the format \fR#
   \fItimestamp_most_recent_event\fR\fR, which gives the
   timestamp of the most recent event in the file.
.sp 2
\fBLimiting the size of lsb.events\fR
.sp 2
   Use MAX_JOB_NUM in lsb.params to set the maximum number of
   finished jobs whose events are to be stored in the lsb.events
   log file.
.sp 2
   Once the limit is reached, mbatchd starts a new event log
   file. The old event log file is saved as lsb.events.\fIn\fR,
   with subsequent sequence number suffixes incremented by 1 each
   time a new log file is started. Event logging continues in the
   new lsb.events file.
.sp 2
\fBRecords and fields\fR
.sp 2
   The fields of a record are separated by blanks. The first
   string of an event record indicates its type. The following
   types of events are recorded:
.sp 2
     o  
         JOB_NEW
.sp 2
     o  
         JOB_FORWARD
.sp 2
     o  
         JOB_ACCEPT
.sp 2
     o  
         JOB_START
.sp 2
     o  
         JOB_START_ACCEPT
.sp 2
     o  
         JOB_STATUS
.sp 2
     o  
         JOB_SWITCH
.sp 2
     o  
         JOB_MOVE
.sp 2
     o  
         QUEUE_CTRL
.sp 2
     o  
         HOST_CTRL
.sp 2
     o  
         MBD_START
.sp 2
     o  
         MBD_DIE
.sp 2
     o  
         UNFULFILL
.sp 2
     o  
         LOAD_INDEX
.sp 2
     o  
         JOB_SIGACT
.sp 2
     o  
         MIG
.sp 2
     o  
         JOB_MODIFY2
.sp 2
     o  
         JOB_SIGNAL
.sp 2
     o  
         JOB_EXECUTE
.sp 2
     o  
         JOB_REQUEUE
.sp 2
     o  
         JOB_CLEAN
.sp 2
     o  
         JOB_EXCEPTION
.sp 2
     o  
         JOB_EXT_MSG
.sp 2
     o  
         JOB_ATTA_DATA
.sp 2
     o  
         JOB_CHUNK
.sp 2
     o  
         SBD_UNREPORTED_STATUS
.sp 2
     o  
         PRE_EXEC_START
.sp 2
     o  
         JOB_FORCE
.sp 2
     o  
         GRP_ADD
.sp 2
     o  
         GRP_MOD
.sp 2
     o  
         LOG_SWITCH
.sp 2
     o  
         JOB_RESIZE_NOTIFY_START
.sp 2
     o  
         JOB_RESIZE_NOTIFY_ACCEPT
.sp 2
     o  
         JOB_RESIZE_NOTIFY_DONE
.sp 2
     o  
         JOB_RESIZE_RELEASE
.sp 2
     o  
         JOB_RESIZE_CANCEL
.sp 2
\fBJOB_NEW\fR
.sp 2
   A new job has been submitted. The fields in order of
   occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the submitter
.sp 2
   \fBoptions (%d)\fR
.br
               Bit flags for job processing
.sp 2
   \fBnumProcessors (%d)\fR
.br
               Number of processors requested for execution
.sp 2
   \fBsubmitTime (%d)\fR
.br
               Job submission time
.sp 2
   \fBbeginTime (%d)\fR
.br
               Start time – the job should be started on or after
               this time
.sp 2
   \fBtermTime (%d)\fR
.br
               Termination deadline – the job should be
               terminated by this time (%d)
.sp 2
   \fBsigValue (%d)\fR
.br
               Signal value
.sp 2
   \fBchkpntPeriod (%d)\fR
.br
               Checkpointing period
.sp 2
   \fBrestartPid (%d)\fR
.br
               Restart process ID
.sp 2
   \fBuserName (%s)\fR
.br
               User name
.sp 2
   \fBrLimits\fR
.br
               Soft CPU time limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft file size limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft data segment size limit (%d), see
               getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft stack segment size limit (%d), see
               getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft core file size limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft memory size limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBrLimits\fR
.br
               Soft run time limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBhostSpec (%s)\fR
.br
               Model or host name for normalizing CPU time and
               run time
.sp 2
   \fBhostFactor (%f)\fR
.br
               CPU factor of the above host
.sp 2
   \fBumask (%d)\fR
.br
               File creation mask for this job
.sp 2
   \fBqueue (%s)\fR
.br
               Name of job queue to which the job was submitted
.sp 2
   \fBresReq (%s)\fR
.br
               Resource requirements
.sp 2
   \fBfromHost (%s)\fR
.br
               Submission host name
.sp 2
   \fBcwd (%s)\fR
.br
               Current working directory (up to 4094 characters
               for UNIX or 255 characters for Windows)
.sp 2
   \fBchkpntDir (%s)\fR
.br
               Checkpoint directory
.sp 2
   \fBinFile (%s)\fR
.br
               Input file name (up to 4094 characters for UNIX or
               255 characters for Windows)
.sp 2
   \fBoutFile (%s)\fR
.br
               Output file name (up to 4094 characters for UNIX
               or 255 characters for Windows)
.sp 2
   \fBerrFile (%s)\fR
.br
               Error output file name (up to 4094 characters for
               UNIX or 255 characters for Windows)
.sp 2
   \fBsubHomeDir (%s)\fR
.br
               Submitter’s home directory
.sp 2
   \fBjobFile (%s)\fR
.br
               Job file name
.sp 2
   \fBnumAskedHosts (%d)\fR
.br
               Number of candidate host names
.sp 2
   \fBaskedHosts (%s)\fR
.br
               List of names of candidate hosts for job
               dispatching
.sp 2
   \fBdependCond (%s)\fR
.br
               Job dependency condition
.sp 2
   \fBpreExecCmd (%s)\fR
.br
               Job pre-execution command
.sp 2
   \fBjobName (%s)\fR
.br
               Job name (up to 4094 characters)
.sp 2
   \fBcommand (%s)\fR
.br
               Job command (up to 4094 characters for UNIX or 255
               characters for Windows)
.sp 2
   \fBnxf (%d)\fR
.br
               Number of files to transfer (%d)
.sp 2
   \fBxf (%s)\fR
.br
               List of file transfer specifications
.sp 2
   \fBmailUser (%s)\fR
.br
               Mail user name
.sp 2
   \fBprojectName (%s)\fR
.br
               Project name
.sp 2
   \fBniosPort (%d)\fR
.br
               Callback port if batch interactive job
.sp 2
   \fBmaxNumProcessors (%d)\fR
.br
               Maximum number of processors
.sp 2
   \fBschedHostType (%s)\fR
.br
               Execution host type
.sp 2
   \fBloginShell (%s)\fR
.br
               Login shell
.sp 2
   \fBtimeEvent (%d)\fR
.br
               Time Event, for job dependency condition;
               specifies when time event ended
.sp 2
   \fBuserGroup (%s)\fR
.br
               User group
.sp 2
   \fBexceptList (%s)\fR
.br
               Exception handlers for the job
.sp 2
   \fBoptions2 (%d)\fR
.br
               Bit flags for job processing
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBinFileSpool (%s)\fR
.br
               Spool input file (up to 4094 characters for UNIX
               or 255 characters for Windows)
.sp 2
   \fBcommandSpool (%s)\fR
.br
               Spool command file (up to 4094 characters for UNIX
               or 255 characters for Windows)
.sp 2
   \fBjobSpoolDir (%s)\fR
.br
               Job spool directory (up to 4094 characters for
               UNIX or 255 characters for Windows)
.sp 2
   \fBuserPriority (%d)\fR
.br
               User priority
.sp 2
   \fBrsvId %s\fR
.br
               Advance reservation ID; for example,
               "\fRuser2#0\fR"
.sp 2
   \fBjobGroup (%s)\fR
.br
               The job group under which the job runs
.sp 2
   \fBsla (%s)\fR
.br
               SLA service class name under which the job runs
.sp 2
   \fBrLimits\fR
.br
               Thread number limit
.sp 2
   \fBextsched (%s)\fR
.br
               External scheduling options
.sp 2
   \fBwarningAction (%s)\fR
.br
               Job warning action
.sp 2
   \fBwarningTimePeriod (%d)\fR
.br
               Job warning time period in seconds
.sp 2
   \fBSLArunLimit (%d)\fR
.br
               Absolute run time limit of the job for SLA service
               classes
.sp 2
   \fBlicenseProject (%s)\fR
.br
               LSF License Scheduler project name
.sp 2
   \fBoptions3 (%d)\fR
.br
               Bit flags for job processing
.sp 2
   \fBapp (%s)\fR
.br
               Application profile name
.sp 2
   \fBpostExecCmd (%s)\fR
.br
               Post-execution command to run on the execution
               host after the job finishes
.sp 2
   \fBruntimeEstimation (%d)\fR
.br
               Estimated run time for the job
.sp 2
   \fBrequeueEValues (%s)\fR
.br
               Job exit values for automatic job requeue
.sp 2
   \fBresizeNotifyCmd (%s)\fR
.br
               Resize notification command to run on the first
               execution host to inform job of a resize event.
.sp 2
   \fBjobDescription (%s)\fR
.br
               Job description (up to 4094 characters).
.sp 2
\fBJOB_FORWARD\fR
.sp 2
   A job has been forwarded to a remote cluster (Platform
   MultiCluster only).
.sp 2
   If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is specified in
   lsf.conf, older daemons and commands (pre-LSF Version 6.0)
   cannot recognize the lsb.events file format.
.sp 2
   The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBnumReserHosts (%d)\fR
.br
               Number of reserved hosts in the remote cluster
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               the number of .hosts listed in the reserHosts
               field.
.sp 2
   \fBcluster (%s)\fR
.br
               Remote cluster name
.sp 2
   \fBreserHosts (%s)\fR
.br
               List of names of the reserved hosts in the remote
               cluster
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               logged in a shortened format.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBJOB_ACCEPT\fR
.sp 2
   A job from a remote cluster has been accepted by this cluster.
   The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID at the accepting cluster
.sp 2
   \fBremoteJid (%d)\fR
.br
               Job ID at the submission cluster
.sp 2
   \fBcluster (%s)\fR
.br
               Job submission cluster name
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBJOB_START\fR
.sp 2
   A job has been dispatched.
.sp 2
   If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is specified in
   lsf.conf, older daemons and commands (pre-LSF Version 6.0)
   cannot recognize the lsb.events file format.
.sp 2
   The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBjStatus (%d)\fR
.br
               Job status, (4, indicating the RUN status of the
               job)
.sp 2
   \fBjobPid (%d)\fR
.br
               Job process ID
.sp 2
   \fBjobPGid (%d)\fR
.br
               Job process group ID
.sp 2
   \fBhostFactor (%f)\fR
.br
               CPU factor of the first execution host
.sp 2
   \fBnumExHosts (%d)\fR
.br
               Number of processors used for execution
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               the number of .hosts listed in the execHosts
               field.
.sp 2
   \fBexecHosts (%s)\fR
.br
               List of execution host names
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               logged in a shortened format.
.sp 2
   \fBqueuePreCmd (%s)\fR
.br
               Pre-execution command
.sp 2
   \fBqueuePostCmd (%s)\fR
.br
               Post-execution command
.sp 2
   \fBjFlags (%d)\fR
.br
               Job processing flags
.sp 2
   \fBuserGroup (%s)\fR
.br
               User group name
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBadditionalInfo (%s)\fR
.br
               Placement information of HPC jobs
.sp 2
   \fBjFlags2 (%d)\fR
.br

.sp 2
\fBJOB_START_ACCEPT\fR
.sp 2
   A job has started on the execution host(s). The fields in
   order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBjobPid (%d)\fR
.br
               Job process ID
.sp 2
   \fBjobPGid (%d)\fR
.br
               Job process group ID
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBJOB_STATUS\fR
.sp 2
   The status of a job changed after dispatch. The fields in
   order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBjStatus (%d)\fR
.br
               New status, see <lsf/lsbatch.h>
.sp 2
   \fBreason (%d)\fR
.br
               Pending or suspended reason code, see
               <lsf/lsbatch.h>
.sp 2
   \fBsubreasons (%d)\fR
.br
               Pending or suspended subreason code, see
               <lsf/lsbatch.h>
.sp 2
   \fBcpuTime (%f)\fR
.br
               CPU time consumed so far
.sp 2
   \fBendTime (%d)\fR
.br
               Job completion time
.sp 2
   \fBru (%d)\fR
.br
               Resource usage flag
.sp 2
   \fBlsfRusage (%s)\fR
.br
               Resource usage statistics, see <lsf/lsf.h>
.sp 2
   \fBexitStatus (%d)\fR
.br
               Exit status of the job, see <lsf/lsbatch.h>
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBexitInfo (%d)\fR
.br
               Job termination reason, see <lsf/lsbatch.h>
.sp 2
   \fBduration4PreemptBackfill\fR
.br
               How long a backfilled job can run; used for
               preemption backfill jobs
.sp 2
\fBJOB_SWITCH\fR
.sp 2
   A job switched from one queue to another (bswitch). The fields
   in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBqueue (%s)\fR
.br
               Target queue name
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the job submitter
.sp 2
\fBJOB_MOVE\fR
.sp 2
   A job moved toward the top or bottom of its queue (bbot or
   btop). The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBposition (%d)\fR
.br
               Position number
.sp 2
   \fBbase (%d)\fR
.br
               Operation code, (TO_TOP or TO_BOTTOM), see
               <lsf/lsbatch.h>
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the job submitter
.sp 2
\fBQUEUE_CTRL\fR
.sp 2
   A job queue has been altered. The fields in order of
   occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBopCode (%d)\fR
.br
               Operation code), see <lsf/lsbatch.h>
.sp 2
   \fBqueue (%s)\fR
.br
               Queue name
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the user
.sp 2
   \fBctrlComments (%s)\fR
.br
               Administrator comment text from the -C option of
               badmin queue control commands qclose, qopen, qact,
               and qinact
.sp 2
\fBHOST_CTRL\fR
.sp 2
   A batch server host changed status. The fields in order of
   occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBopCode (%d)\fR
.br
               Operation code, see <lsf/lsbatch.h>
.sp 2
   \fBhost (%s)\fR
.br
               Host name
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the user
.sp 2
   \fBctrlComments (%s)\fR
.br
               Administrator comment text from the -C option of
               badmin host control commands hclose and hopen
.sp 2
\fBMBD_START\fR
.sp 2
   The mbatchd has started. The fields in order of occurrence
   are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBmaster (%s)\fR
.br
               Master host name
.sp 2
   \fBcluster (%s)\fR
.br
               cluster name
.sp 2
   \fBnumHosts (%d)\fR
.br
               Number of hosts in the cluster
.sp 2
   \fBnumQueues (%d)\fR
.br
               Number of queues in the cluster
.sp 2
\fBMBD_DIE\fR
.sp 2
   The mbatchd died. The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBmaster (%s)\fR
.br
               Master host name
.sp 2
   \fBnumRemoveJobs (%d)\fR
.br
               Number of finished jobs that have been removed
               from the system and logged in the current event
               file
.sp 2
   \fBexitCode (%d)\fR
.br
               Exit code from mbatchd
.sp 2
   \fBctrlComments (%s)\fR
.br
               Administrator comment text from the -C option of
               badmin mbdrestart
.sp 2
\fBUNFULFILL\fR
.sp 2
   Actions that were not taken because the mbatchd was unable to
   contact the sbatchd on the job execution host. The fields in
   order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBnotSwitched (%d)\fR
.br
               Not switched: the mbatchd has switched the job to
               a new queue, but the sbatchd has not been informed
               of the switch
.sp 2
   \fBsig (%d)\fR
.br
               Signal: this signal has not been sent to the job
.sp 2
   \fBsig1 (%d)\fR
.br
               Checkpoint signal: the job has not been sent this
               signal to checkpoint itself
.sp 2
   \fBsig1Flags (%d)\fR
.br
               Checkpoint flags, see <lsf/lsbatch.h>
.sp 2
   \fBchkPeriod (%d) \fR
.br
               New checkpoint period for job
.sp 2
   \fBnotModified (%s)\fR
.br
               If set to true, then parameters for the job cannot
               be modified.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBLOAD_INDEX\fR
.sp 2
   mbatchd restarted with these load index names (see
   lsf.cluster(5)). The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBnIdx (%d)\fR
.br
               Number of index names
.sp 2
   \fBname (%s)\fR
.br
               List of index names
.sp 2
\fBJOB_SIGACT\fR
.sp 2
   An action on a job has been taken. The fields in order of
   occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBperiod (%d)\fR
.br
               Action period
.sp 2
   \fBpid (%d)\fR
.br
               Process ID of the child sbatchd that initiated the
               action
.sp 2
   \fBjstatus (%d)\fR
.br
               Job status
.sp 2
   \fBreasons (%d)\fR
.br
               Job pending reasons
.sp 2
   \fBflags (%d)\fR
.br
               Action flags, see <lsf/lsbatch.h>
.sp 2
   \fBactStatus (%d)\fR
.br
               Action status:
.sp 2
               1: Action started
.sp 2
               2: One action preempted other actions
.sp 2
               3: Action succeeded
.sp 2
               4: Action Failed
.sp 2
   \fBsignalSymbol (%s)\fR
.br
               Action name, accompanied by actFlags
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBMIG\fR
.sp 2
   A job has been migrated (bmig). The fields in order of
   occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBnumAskedHosts (%d)\fR
.br
               Number of candidate hosts for migration
.sp 2
   \fBaskedHosts (%s)\fR
.br
               List of names of candidate hosts
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the job submitter
.sp 2
\fBJOB_MODIFY2\fR
.sp 2
   This is created when the mbatchd modifies a previously
   submitted job with bmod.
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobIdStr (%s)\fR
.br
               Job ID
.sp 2
   \fBoptions (%d)\fR
.br
               Bit flags for job modification options processing
.sp 2
   \fBoptions2 (%d)\fR
.br
               Bit flags for job modification options processing
.sp 2
   \fBdelOptions (%d)\fR
.br
               Delete options for the options field
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the submitter
.sp 2
   \fBuserName (%s)\fR
.br
               User name
.sp 2
   \fBsubmitTime (%d)\fR
.br
               Job submission time
.sp 2
   \fBumask (%d)\fR
.br
               File creation mask for this job
.sp 2
   \fBnumProcessors (%d)\fR
.br
               Number of processors requested for execution. The
               value 2147483646 means the number of processors is
               undefined.
.sp 2
   \fBbeginTime (%d)\fR
.br
               Start time – the job should be started on or after
               this time
.sp 2
   \fBtermTime (%d)\fR
.br
               Termination deadline – the job should be
               terminated by this time
.sp 2
   \fBsigValue (%d)\fR
.br
               Signal value
.sp 2
   \fBrestartPid (%d)\fR
.br
               Restart process ID for the original job
.sp 2
   \fBjobName (%s)\fR
.br
               Job name (up to 4094 characters)
.sp 2
   \fBqueue (%s)\fR
.br
               Name of job queue to which the job was submitted
.sp 2
   \fBnumAskedHosts (%d)\fR
.br
               Number of candidate host names
.sp 2
   \fBaskedHosts (%s)\fR
.br
               List of names of candidate hosts for job
               dispatching; blank if the last field value is 0.
               If there is more than one host name, then each
               additional host name will be returned in its own
               field
.sp 2
   \fBresReq (%s)\fR
.br
               Resource requirements
.sp 2
   \fBrLimits\fR
.br
               Soft CPU time limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft file size limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft data segment size limit (%d), see getrlimit2)
.sp 2
   \fBrLimits\fR
.br
               Soft stack segment size limit (%d), see
               getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft core file size limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Soft memory size limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBrLimits\fR
.br
               Soft run time limit (%d), see getrlimit(2)
.sp 2
   \fBrLimits\fR
.br
               Reserved (%d)
.sp 2
   \fBhostSpec (%s)\fR
.br
               Model or host name for normalizing CPU time and
               run time
.sp 2
   \fBdependCond (%s)\fR
.br
               Job dependency condition
.sp 2
   \fBtimeEvent (%d)\fR
.br
               Time Event, for job dependency condition;
               specifies when time event ended
.sp 2
   \fBsubHomeDir (%s)\fR
.br
               Submitter’s home directory
.sp 2
   \fBinFile (%s)\fR
.br
               Input file name (up to 4094 characters for UNIX or
               255 characters for Windows)
.sp 2
   \fBoutFile (%s)\fR
.br
               Output file name (up to 4094 characters for UNIX
               or 255 characters for Windows)
.sp 2
   \fBerrFile (%s)\fR
.br
               Error output file name (up to 4094 characters for
               UNIX or 255 characters for Windows)
.sp 2
   \fBcommand (%s)\fR
.br
               Job command (up to 4094 characters for UNIX or 255
               characters for Windows)
.sp 2
   \fBchkpntPeriod (%d)\fR
.br
               Checkpointing period
.sp 2
   \fBchkpntDir (%s)\fR
.br
               Checkpoint directory
.sp 2
   \fBnxf (%d)\fR
.br
               Number of files to transfer
.sp 2
   \fBxf (%s)\fR
.br
               List of file transfer specifications
.sp 2
   \fBjobFile (%s)\fR
.br
               Job file name
.sp 2
   \fBfromHost (%s)\fR
.br
               Submission host name
.sp 2
   \fBcwd (%s)\fR
.br
               Current working directory (up to 4094 characters
               for UNIX or 255 characters for Windows)
.sp 2
   \fBpreExecCmd (%s)\fR
.br
               Job pre-execution command
.sp 2
   \fBmailUser (%s)\fR
.br
               Mail user name
.sp 2
   \fBprojectName (%s)\fR
.br
               Project name
.sp 2
   \fBniosPort (%d)\fR
.br
               Callback port if batch interactive job
.sp 2
   \fBmaxNumProcessors (%d)\fR
.br
               Maximum number of processors. The value 2147483646
               means the maximum number of processors is
               undefined.
.sp 2
   \fBloginShell (%s)\fR
.br
               Login shell
.sp 2
   \fBschedHostType (%s)\fR
.br
               Execution host type
.sp 2
   \fBuserGroup (%s)\fR
.br
               User group
.sp 2
   \fBexceptList (%s)\fR
.br
               Exception handlers for the job
.sp 2
   \fBdelOptions2 (%d)\fR
.br
               Delete options for the options2 field
.sp 2
   \fBinFileSpool (%s)\fR
.br
               Spool input file (up to 4094 characters for UNIX
               or 255 characters for Windows)
.sp 2
   \fBcommandSpool (%s)\fR
.br
               Spool command file (up to 4094 characters for UNIX
               or 255 characters for Windows)
.sp 2
   \fBuserPriority (%d)\fR
.br
               User priority
.sp 2
   \fBrsvId %s\fR
.br
               Advance reservation ID; for example,
               "\fRuser2#0\fR"
.sp 2
   \fBextsched (%s) \fR
.br
               External scheduling options
.sp 2
   \fBwarningTimePeriod (%d)\fR
.br
               Job warning time period in seconds
.sp 2
   \fBwarningAction (%s)\fR
.br
               Job warning action
.sp 2
   \fBjobGroup (%s)\fR
.br
               The job group to which the job is attached
.sp 2
   \fBsla (%s)\fR
.br
               SLA service class name that the job is to be
               attached to
.sp 2
   \fBlicenseProject (%s)\fR
.br
               LSF License Scheduler project name
.sp 2
   \fBoptions3 (%d)\fR
.br
               Bit flags for job processing
.sp 2
   \fBdelOption3 (%d)\fR
.br
               Delete options for the options3 field
.sp 2
   \fBapp (%s)\fR
.br
               Application profile name
.sp 2
   \fBapsString (%s)\fR
.br
               Absolute priority scheduling (APS) value set by
               administrator
.sp 2
   \fBpostExecCmd (%s)\fR
.br
               Post-execution command to run on the execution
               host after the job finishes
.sp 2
   \fBruntimeEstimation (%d)\fR
.br
               Estimated run time for the job
.sp 2
   \fBrequeueEValues (%s)\fR
.br
               Job exit values for automatic job requeue
.sp 2
   \fBresizeNotifyCmd (%s)\fR
.br
               Resize notification command to run on the first
               execution host to inform job of a resize event.
.sp 2
   \fBjobdescription (%s)\fR
.br
               Job description (up to 4094 characters).
.sp 2
\fBJOB_SIGNAL\fR
.sp 2
   This is created when a job is signaled with bkill or deleted
   with bdel. The fields are in the order they appended:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command
.sp 2
   \fBrunCount (%d)\fR
.br
               Number of runs
.sp 2
   \fBsignalSymbol (%s)\fR
.br
               Signal name
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the job submitter
.sp 2
\fBJOB_EXECUTE\fR
.sp 2
   This is created when a job is actually running on an execution
   host. The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBexecUid (%d)\fR
.br
               Mapped UNIX user ID on execution host
.sp 2
   \fBjobPGid (%d)\fR
.br
               Job process group ID
.sp 2
   \fBexecCwd (%s)\fR
.br
               Current working directory job used on execution
               host (up to 4094 characters for UNIX or 255
               characters for Windows)
.sp 2
   \fBexecHome (%s)\fR
.br
               Home directory job used on execution host
.sp 2
   \fBexecUsername (%s)\fR
.br
               Mapped user name on execution host
.sp 2
   \fBjobPid (%d)\fR
.br
               Job process ID
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBadditionalInfo (%s)\fR
.br
               Placement information of HPC jobs
.sp 2
   \fBSLAscaledRunLimit (%d)\fR
.br
               Run time limit for the job scaled by the execution
               host
.sp 2
   \fBexecRusage\fR
.br
               An internal field used by LSF.
.sp 2
   \fBPosition\fR
.br
               An internal field used by LSF.
.sp 2
   \fBduration4PreemptBackfill\fR
.br
               How long a backfilled job can run; used for
               preemption backfill jobs
.sp 2
\fBJOB_REQUEUE\fR
.sp 2
   This is created when a job ended and requeued by mbatchd. The
   fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBJOB_CLEAN\fR
.sp 2
   This is created when a job is removed from the mbatchd memory.
   The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBJOB_EXCEPTION\fR
.sp 2
   This is created when an exception condition is detected for a
   job. The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBexceptMask (%d)\fR
.br
               Exception Id
.sp 2
               0x01: missched
.sp 2
               0x02: overrun
.sp 2
               0x04: underrun
.sp 2
               0x08: abend
.sp 2
               0x10: cantrun
.sp 2
               0x20: hostfail
.sp 2
               0x40: startfail
.sp 2
               0x100:runtime_est_exceeded
.sp 2
   \fBactMask (%d)\fR
.br
               Action Id
.sp 2
               0x01: kill
.sp 2
               0x02: alarm
.sp 2
               0x04: rerun
.sp 2
               0x08: setexcept
.sp 2
   \fBtimeEvent (%d)\fR
.br
               Time Event, for \fRmissched\fR exception specifies
               when time event ended.
.sp 2
   \fBexceptInfo (%d)\fR
.br
               Except Info, pending reason for \fRmissched\fR or
               \fRcantrun\fR exception, the exit code of the job
               for the \fRabend\fR exception, otherwise 0.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
\fBJOB_EXT_MSG\fR
.sp 2
   An external message has been sent to a job. The fields in
   order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBmsgIdx (%d)\fR
.br
               Index in the list
.sp 2
   \fBuserId (%d)\fR
.br
               Unique user ID of the user invoking the command
.sp 2
   \fBdataSize (%ld)\fR
.br
               Size of the data if it has any, otherwise 0
.sp 2
   \fBpostTime (%ld)\fR
.br
               Message sending time
.sp 2
   \fBdataStatus (%d)\fR
.br
               Status of the attached data
.sp 2
   \fBdesc (%s)\fR
.br
               Text description of the message
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the author of the message
.sp 2
\fBJOB_ATTA_DATA\fR
.sp 2
   An update on the data status of a message for a job has been
   sent. The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBmsgIdx (%d)\fR
.br
               Index in the list
.sp 2
   \fBdataSize (%ld)\fR
.br
               Size of the data if is has any, otherwise 0
.sp 2
   \fBdataStatus (%d)\fR
.br
               Status of the attached data
.sp 2
   \fBfileName (%s)\fR
.br
               File name of the attached data
.sp 2
\fBJOB_CHUNK\fR
.sp 2
   This is created when a job is inserted into a chunk.
.sp 2
   If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is specified in
   lsf.conf, older daemons and commands (pre-LSF Version 6.0)
   cannot recognize the lsb.events file format.
.sp 2
   The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBmembSize (%ld)\fR
.br
               Size of array membJobId
.sp 2
   \fBmembJobId (%ld)\fR
.br
               Job IDs of jobs in the chunk
.sp 2
   \fBnumExHosts (%ld)\fR
.br
               Number of execution hosts
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               the number of .hosts listed in the execHosts
               field.
.sp 2
   \fBexecHosts (%s)\fR
.br
               Execution host name array
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               logged in a shortened format.
.sp 2
\fBSBD_UNREPORTED_STATUS\fR
.sp 2
   This is created when an unreported status change occurs. The
   fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBactPid (%d)\fR
.br
               Acting processing ID
.sp 2
   \fBjobPid (%d)\fR
.br
               Job process ID
.sp 2
   \fBjobPGid (%d)\fR
.br
               Job process group ID
.sp 2
   \fBnewStatus (%d)\fR
.br
               New status of the job
.sp 2
   \fBreason (%d)\fR
.br
               Pending or suspending reason code, see
               <lsf/lsbatch.h>
.sp 2
   \fBsuspreason (%d)\fR
.br
               Pending or suspending subreason code, see
               <lsf/lsbatch.h>
.sp 2
   \fBlsfRusage\fR
.br
               The following fields contain resource usage
               information for the job (see getrusage(2)). If the
               value of some field is unavailable (due to job
               exit or the difference among the operating
               systems), -1 will be logged. Times are measured in
               seconds, and sizes are measured in KB.
.sp 2
               \fBru_utime (%f)\fR
.br
                           User time used
.sp 2
               \fBru_stime (%f)\fR
.br
                           System time used
.sp 2
               \fBru_maxrss (%f)\fR
.br
                           Maximum shared text size
.sp 2
               \fBru_ixrss (%f)\fR
.br
                           Integral of the shared text size over
                           time (in KB seconds)
.sp 2
               \fBru_ismrss (%f)\fR
.br
                           Integral of the shared memory size
                           over time (valid only on Ultrix)
.sp 2
               \fBru_idrss (%f)\fR
.br
                           Integral of the unshared data size
                           over time
.sp 2
               \fBru_isrss (%f)\fR
.br
                           Integral of the unshared stack size
                           over time
.sp 2
               \fBru_minflt (%f)\fR
.br
                           Number of page reclaims
.sp 2
               \fBru_majflt (%f)\fR
.br
                           Number of page faults
.sp 2
               \fBru_nswap (%f)\fR
.br
                           Number of times the process was
                           swapped out
.sp 2
               \fBru_inblock (%f)\fR
.br
                           Number of block input operations
.sp 2
               \fBru_oublock (%f)\fR
.br
                           Number of block output operations
.sp 2
               \fBru_ioch (%f)\fR
.br
                           Number of characters read and written
                           (valid only on HP-UX)
.sp 2
               \fBru_msgsnd (%f)\fR
.br
                           Number of System V IPC messages sent
.sp 2
               \fBru_msgrcv (%f)\fR
.br
                           Number of messages received
.sp 2
               \fBru_nsignals (%f)\fR
.br
                           Number of signals received
.sp 2
               \fBru_nvcsw (%f)\fR
.br
                           Number of voluntary context switches
.sp 2
               \fBru_nivcsw (%f)\fR
.br
                           Number of involuntary context switches
.sp 2
               \fBru_exutime (%f)\fR
.br
                           Exact user time used (valid only on
                           ConvexOS)
.sp 2
   \fBexitStatus (%d)\fR
.br
               Exit status of the job, see <lsf/lsbatch.h>
.sp 2
   \fBexecCwd (%s)\fR
.br
               Current working directory job used on execution
               host (up to 4094 characters for UNIX or 255
               characters for Windows)
.sp 2
   \fBexecHome (%s)\fR
.br
               Home directory job used on execution host
.sp 2
   \fBexecUsername (%s)\fR
.br
               Mapped user name on execution host
.sp 2
   \fBmsgId (%d)\fR
.br
               ID of the message
.sp 2
   \fBactStatus (%d)\fR
.br
               Action status
.sp 2
               1: Action started
.sp 2
               2: One action preempted other actions
.sp 2
               3: Action succeeded
.sp 2
               4: Action Failed
.sp 2
   \fBsigValue (%d)\fR
.br
               Signal value
.sp 2
   \fBseq (%d)\fR
.br
               Sequence status of the job
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBjRusage\fR
.br
               The following fields contain resource usage
               information for the job. If the value of some
               field is unavailable (due to job exit or the
               difference among the operating systems), -1 will
               be logged. Times are measured in seconds, and
               sizes are measured in KB.
.sp 2
               \fBmem (%d)\fR
.br
                           Total resident memory usage in KB of
                           all currently running processes in a
                           given process group
.sp 2
               \fBswap (%d)\fR
.br
                           Totaly virtual memory usage in KB of
                           all currently running processes in
                           given process groups
.sp 2
               \fButime (%d)\fR
.br
                           Cumulative total user time in seconds
.sp 2
               \fBstime (%d)\fR
.br
                           Cumulative total system time in
                           seconds
.sp 2
               \fBnpids (%d)\fR
.br
                           Number of currently active process in
                           given process groups. This entry has
                           four sub-fields:
.sp 2
               \fBpid (%d)\fR
.br
                           Process ID of the child sbatchd that
                           initiated the action
.sp 2
               \fBppid (%d)\fR
.br
                           Parent process ID
.sp 2
               \fBpgid (%d)\fR
.br
                           Process group ID
.sp 2
               \fBjobId (%d)\fR
.br
                           Process Job ID
.sp 2
               \fBnpgids (%d)\fR
.br
                           Number of currently active process
                           groups
.sp 2
   \fBexitInfo (%d)\fR
.br
               Job termination reason, see <lsf/lsbatch.h>
.sp 2
\fBPRE_EXEC_START\fR
.sp 2
   A pre-execution command has been started.
.sp 2
   The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBjStatus (%d)\fR
.br
               Job status, (4, indicating the RUN status of the
               job)
.sp 2
   \fBjobPid (%d)\fR
.br
               Job process ID
.sp 2
   \fBjobPGid (%d)\fR
.br
               Job process group ID
.sp 2
   \fBhostFactor (%f)\fR
.br
               CPU factor of the first execution host
.sp 2
   \fBnumExHosts (%d)\fR
.br
               Number of processors used for execution
.sp 2
   \fBexecHosts (%s)\fR
.br
               List of execution host names
.sp 2
   \fBqueuePreCmd (%s)\fR
.br
               Pre-execution command
.sp 2
   \fBqueuePostCmd (%s)\fR
.br
               Post-execution command
.sp 2
   \fBjFlags (%d)\fR
.br
               Job processing flags
.sp 2
   \fBuserGroup (%s)\fR
.br
               User group name
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBadditionalInfo (%s)\fR
.br
               Placement information of HPC jobs
.sp 2
\fBJOB_FORCE\fR
.sp 2
   A job has been forced to run with brun.
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command
.sp 2
   \fBidx (%d)\fR
.br
               Job array index
.sp 2
   \fBoptions (%d)\fR
.br
               Bit flags for job processing
.sp 2
   \fBnumExecHosts (%ld)\fR
.br
               Number of execution hosts
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               the number of .hosts listed in the execHosts
               field.
.sp 2
   \fBexecHosts (%s)\fR
.br
               Execution host name array
.sp 2
               If LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is
               specified in lsf.conf, the value of this field is
               logged in a shortened format.
.sp 2
   \fBuserName (%s)\fR
.br
               Name of the user
.sp 2
   \fBqueue (%s)\fR
.br
               Name of queue if a remote brun job ran; otherwise,
               this field is empty
.sp 2
\fBGRP_ADD\fR
.sp 2
   This is created when a job group is added. The fields in order
   of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the job group owner
.sp 2
   \fBsubmitTime (%d)\fR
.br
               Job submission time
.sp 2
   \fBuserName (%s)\fR
.br
               User name of the job group owner
.sp 2
   \fBdepCond (%s)\fR
.br
               Job dependency condition
.sp 2
   \fBtimeEvent (%d)\fR
.br
               Time Event, for job dependency condition;
               specifies when time event ended
.sp 2
   \fBgroupSpec (%s)\fR
.br
               Job group name
.sp 2
   \fBdelOptions (%d)\fR
.br
               Delete options for the options field
.sp 2
   \fBdelOptions2 (%d)\fR
.br
               Delete options for the options2 field
.sp 2
   \fBsla (%s)\fR
.br
               SLA service class name that the job group is to be
               attached to
.sp 2
   \fBmaxJLimit (%d)\fR
.br
               Job group limit set by bgadd -L
.sp 2
   \fBgroupType (%d)\fR
.br
               Job group creation method:
.sp 2
                 o  
                     0x01 - job group was created explicitly
.sp 2
                 o  
                     0x02 - job group was created implicitly
.sp 2
\fBGRP_MOD\fR
.sp 2
   This is created when a job group is modified. The fields in
   order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the job group owner
.sp 2
   \fBsubmitTime (%d)\fR
.br
               Job submission time
.sp 2
   \fBuserName (%s)\fR
.br
               User name of the job group owner
.sp 2
   \fBdepCond (%s)\fR
.br
               Job dependency condition
.sp 2
   \fBtimeEvent (%d)\fR
.br
               Time Event, for job dependency condition;
               specifies when time event ended
.sp 2
   \fBgroupSpec (%s)\fR
.br
               Job group name
.sp 2
   \fBdelOptions (%d)\fR
.br
               Delete options for the options field
.sp 2
   \fBdelOptions2 (%d)\fR
.br
               Delete options for the options2 field
.sp 2
   \fBsla (%s)\fR
.br
               SLA service class name that the job group is to be
               attached to
.sp 2
   \fBmaxJLimit (%d)\fR
.br
               Job group limit set by bgmod -L
.sp 2
\fBLOG_SWITCH\fR
.sp 2
   This is created when switching the event file lsb.events. The
   fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event
.sp 2
   \fBjobId (%d)\fR
.br
               Job ID
.sp 2
\fBJOB_RESIZE_NOTIFY_START\fR
.sp 2
   LSF logs this event when a resize (shrink or grow) request has
   been sent to the first execution host. The fields in order of
   occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number.
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event.
.sp 2
   \fBjobId (%d)\fR
.br
               The job ID.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index.
.sp 2
   \fBnotifyId (%d)\fR
.br
               Identifier or handle for notification.
.sp 2
   \fBnumResizeHosts (%d)\fR
.br
               Number of processors used for execution. If
               LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is specified
               in lsf.conf, the value of this field is the number
               of hosts listed in short format.
.sp 2
   \fBresizeHosts (%s)\fR
.br
               List of execution host names. If
               LSF_HPC_EXTENSIONS="SHORT_EVENTFILE" is specified
               in lsf.conf, the value of this field is logged in
               a shortened format.
.sp 2
\fBJOB_RESIZE_NOTIFY_ACCEPT\fR
.sp 2
   LSF logs this event when a resize request has been accepted
   from the first execution host of a job. The fields in order of
   occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number.
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event.
.sp 2
   \fBjobId (%d)\fR
.br
               The job ID.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index.
.sp 2
   \fBnotifyId (%d)\fR
.br
               Identifier or handle for notification.
.sp 2
   \fBresizeNotifyCmdPid (%d)\fR
.br
               Resize notification executable process ID. If no
               resize notification executable is defined, this
               field will be set to 0.
.sp 2
   \fBresizeNotifyCmdPGid (%d)\fR
.br
               Resize notification executable process group ID.
               If no resize notification executable is defined,
               this field will be set to 0.
.sp 2
   \fBstatus (%d)\fR
.br
               Status field used to indicate possible errors. 0
               Success, 1 failure.
.sp 2
\fBJOB_RESIZE_NOTIFY_DONE\fR
.sp 2
   LSF logs this event when the resize notification command
   completes. The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number.
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event.
.sp 2
   \fBjobId (%d)\fR
.br
               The job ID.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index.
.sp 2
   \fBnotifyId (%d)\fR
.br
               Identifier or handle for notification.
.sp 2
   \fBstatus (%d)\fR
.br
               Resize notification exit value. (0, success, 1,
               failure, 2 failure but cancel request.)
.sp 2
\fBJOB_RESIZE_RELEASE\fR
.sp 2
   LSF logs this event when receiving resource release request
   from client. The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number.
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event.
.sp 2
   \fBjobId (%d)\fR
.br
               The job ID.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index.
.sp 2
   \fBreqid (%d)\fR
.br
               Request Identifier or handle.
.sp 2
   \fBoptions (%d)\fR
.br
               Release options.
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command.
.sp 2
   \fBuserName (%s)\fR
.br
               User name of the submitter.
.sp 2
   \fBresizeNotifyCmd (%s)\fR
.br
               Resize notification command to run on the first
               execution host to inform job of a resize event.
.sp 2
   \fBnumResizeHosts (%d)\fR
.br
               Number of processors used for execution during
               resize. If
               \fBLSF_HPC_EXTENSIONS="SHORT_EVENTFILE"\fR is
               specified in lsf.conf, the value of this field is
               the number of hosts listed in short format.
.sp 2
   \fBresizeHosts (%s)\fR
.br
               List of execution host names during resize. If
               \fBLSF_HPC_EXTENSIONS="SHORT_EVENTFILE"\fR is
               specified in lsf.conf, the value of this field is
               logged in a shortened format.
.sp 2
\fBJOB_RESIZE_CANCEL\fR
.sp 2
   LSF logs this event when receiving cancel request from client.
   The fields in order of occurrence are:
.sp 2
   \fBVersion number (%s)\fR
.br
               The version number.
.sp 2
   \fBEvent time (%d)\fR
.br
               The time of the event.
.sp 2
   \fBjobId (%d)\fR
.br
               The job ID.
.sp 2
   \fBidx (%d)\fR
.br
               Job array index.
.sp 2
   \fBuserId (%d)\fR
.br
               UNIX user ID of the user invoking the command.
.sp 2
   \fBuserName (%s)\fR
.br
               User name of the submitter.
