
.ad l

.ll 72

.TH lsf.sudoers 5 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBlsf.sudoers\fR
.sp 2

.sp 2 .SH "About lsf.sudoers"
\fBAbout lsf.sudoers\fR
.sp 2
   The lsf.sudoers file is an optional file to configure security
   mechanisms. It is not installed by default.
.sp 2
   You use lsf.sudoers to set the parameter LSF_EAUTH_KEY to
   configure a key for \fReauth\fR to encrypt and decrypt user
   authentication data.
.sp 2
   On UNIX, you also use lsf.sudoers to grant permission to users
   other than root to perform certain operations as root in LSF,
   or as a specified user.
.sp 2
   These operations include:
.sp 2
     o  
         LSF daemon startup/shutdown
.sp 2
     o  
         User ID for LSF authentication
.sp 2
     o  
         User ID for LSF pre- and post-execution commands.
.sp 2
     o  
         User ID for external LSF executables
.sp 2
   If lsf.sudoers does not exist, only root can perform these
   operations in LSF on UNIX.
.sp 2
   On UNIX, this file is located in /etc.
.sp 2
   There is one \fRlsf.sudoers\fR file per host.
.sp 2
   On Windows, this file is located in the directory specified by
   the parameter LSF_SECUREDIR in lsf.conf.
.sp 2 .SH "Changing lsf.sudoers configuration"
\fBChanging lsf.sudoers configuration\fR
.sp 2
   After making any changes to lsf.sudoers, run badmin reconfig
   to reload the configuration files.
.sp 2 .SH "lsf.sudoers on UNIX"
\fBlsf.sudoers on UNIX\fR
.sp 2
   In LSF, certain operations such as daemon startup can only be
   performed by root. The lsf.sudoers file grants root privileges
   to specific users or user groups to perform these operations.
.sp 2
   \fBLocation\fR
.br
               lsf.sudoers must be located in /etc on each host.
.sp 2
   \fBPermissions\fR
.br
               lsf.sudoers must have permission 600 and be
               readable and writable only by root.
.sp 2 .SH "lsf.sudoers on Windows"
\fBlsf.sudoers on Windows\fR
.sp 2
   The lsf.sudoers file is shared over an NTFS network, not
   duplicated on every Windows host.
.sp 2
   By default, LSF installs lsf.sudoers in the %SYSTEMROOT%
   directory.
.sp 2
   The location of lsf.sudoers on Windows must be specified by
   LSF_SECUREDIR in lsf.conf. You must configure the
   LSF_SECUREDIR parameter in lsf.conf if using lsf.sudoers on
   Windows.
.sp 2 .SH "Windows permissions"
\fBWindows permissions\fR
.sp 2
      \fBRestriction: \fR
.sp 2
         The owner of lsf.sudoers on Windows be
         \fRAdministrators\fR. If not, eauth may not work.
.sp 2
   The permissions on lsf.sudoers for Windows are:
.sp 2
   \fBWorkgroup Environment\fR
.br
                 o  
                     Local Admins (W)
.sp 2
                 o  
                     Everyone (R)
.sp 2
   \fBDomain Environment\fR
.br
                 o  
                     Domain Admins (W)
.sp 2
                 o  
                     Everyone (R)
.sp 2 .SH "File format"
\fBFile format\fR
.sp 2
   The format of lsf.sudoers is very similar to that of lsf.conf.
.sp 2
   Each entry can have one of the following forms:
.sp 2
     o  
         \fRNAME=VALUE\fR
.sp 2
     o  
         \fRNAME=\fR
.sp 2
     o  
         \fRNAME= "STRING1 STRING2 ..."\fR
.sp 2
   The equal sign \fR=\fR must follow each \fRNAME\fR even if no
   value follows and there should be no space beside the equal
   sign.
.sp 2
   \fRNAME\fR describes an authorized operation.
.sp 2
   \fRVALUE\fR is a single string or multiple strings separated
   by spaces and enclosed in quotation marks.
.sp 2
   Lines starting with a pound sign (#) are comments and are
   ignored. Do not use \fR#if\fR as this is reserved syntax for
   time-based configuration.
.sp 2 .SH "Example lsf.sudoers File"
\fBExample lsf.sudoers File\fR
.sp 2
   LSB_PRE_POST_EXEC_USER=user100
.sp 2
   LSF_STARTUP_PATH=/usr/share/lsf/etc
.sp 2
   LSF_STARTUP_USERS="user1 user10 user55"
.sp 2 .SH "Creating and modifying lsf.sudoers"
\fBCreating and modifying lsf.sudoers\fR
.sp 2
   You can create and modify lsf.sudoers with a text editor.
.sp 2
   After you modify lsf.sudoers, you must run badmin hrestart all
   to restart all sbatchds in the cluster with the updated
   configuration.
.sp 2 .SH "Parameters"
\fBParameters\fR
.sp 2
     o  
         LSB_PRE_POST_EXEC_USER
.sp 2
     o  
         LSF_EAUTH_KEY
.sp 2
     o  
         LSF_EAUTH_USER
.sp 2
     o  
         LSF_EEXEC_USER
.sp 2
     o  
         LSF_EGO_ADMIN_PASSWD
.sp 2
     o  
         LSF_EGO_ADMIN_USER
.sp 2
     o  
         LSF_LOAD_PLUGINS
.sp 2
     o  
         LSF_STARTUP_PATH
.sp 2
     o  
         LSF_STARTUP_USERS
.sp 2
\fBLSB_PRE_POST_EXEC_USER\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSB_PRE_POST_EXEC_USER=user_name
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Specifies the UNIX user account under which pre- and
   post-execution commands run. This parameter applies only to
   pre- and post-execution commands configured at the application
   and queue levels; pre-execution commands defined at the job
   level with bsub -E run under the account of the user who
   submits the job.
.sp 2
   You can specify only one user account. If the pre-execution or
   post-execution commands perform privileged operations that
   require root permissions on UNIX hosts, specify a value of
   root.
.sp 2
   If you configure this parameter as root, the \fBLD_PRELOAD\fR
   \fBand LD_LIBRARY_PATH\fR variables are removed from the
   pre-execution, post-execution, and eexec environments for
   security purposes.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. Pre-execution and post-execution commands run
   under the user account of the user who submits the job.
.sp 2
\fBLSF_EAUTH_KEY \fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSF_EAUTH_KEY=key
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Applies to UNIX, Windows, and mixed UNIX/Windows clusters.
.sp 2
   Specifies the key that eauth uses to encrypt and decrypt user
   authentication data. Defining this parameter enables increased
   security at your site. The key must contain at least six
   characters and must use only printable characters.
.sp 2
   For UNIX, you must edit the lsf.sudoers file on all hosts
   within the cluster and specify the same encryption key. For
   Windows, you must edit the shared lsf.sudoers file.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. The \fReauth\fR executable encrypts and decrypts
   authentication data using an internal key.
.sp 2
\fBLSF_EAUTH_USER\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSF_EAUTH_USER=user_name
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   UNIX only.
.sp 2
   Specifies the UNIX user account under which the external
   authentication executable eauth runs.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. The \fReauth\fR executable runs under the account
   of the primary LSF administrator.
.sp 2
\fBLSF_EEXEC_USER\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
   \fRLSF_EEXEC_USER=\fR\fIuser_name\fR
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   UNIX only.
.sp 2
   Specifies the UNIX user account under which the external
   executable eexec runs.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. The eexec executable runs under root or the
   account of the user who submitted the job.
.sp 2
\fBLSF_EGO_ADMIN_PASSWD\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSF_EGO_ADMIN_PASSWD=password
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   When the EGO Service Controller (EGOSC) is configured to
   control LSF daemons, enables UNIX and Windows users to bypass
   the additional login required to start res and sbatchd.
   Bypassing the EGO administrator login enables the use of
   scripts to automate system startup.
.sp 2
   Specify the Admin EGO cluster administrator password as clear
   text. You must also define the \fBLSF_EGO_ADMIN_USER\fR
   parameter.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. With EGOSC daemon control enabled, the lsadmin
   and badmin startup subcommands invoke the egosh \fIuser
   logon\fR command to prompt for the Admin EGO cluster
   administrator credentials.
.sp 2
\fBLSF_EGO_ADMIN_USER\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSF_EGO_ADMIN_USER=Admin
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   When the EGO Service Controller (EGOSC) is configured to
   control LSF daemons, enables UNIX and Windows users to bypass
   the additional login required to start res and sbatchd.
   Bypassing the EGO administrator login enables the use of
   scripts to automate system startup.
.sp 2
   Specify the Admin EGO cluster administrator account. You must
   also define the \fBLSF_EGO_ADMIN_PASSWD\fR parameter.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. With EGOSC daemon control enabled, the lsadmin
   and badmin startup subcommands invoke the egosh \fIuser
   logon\fR command to prompt for the Admin EGO cluster
   administrator credentials.
.sp 2
\fBLSF_LOAD_PLUGINS\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSF_LOAD_PLUGINS=y | Y
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   If defined, LSF loads plugins from \fBLSB_LSBDIR\fR. Used for
   Kerberos authentication and to enable the LSF cpuset plugin
   for IRIX.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. LSF does not load plugins.
.sp 2
\fBLSF_STARTUP_PATH\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSF_STARTUP_PATH=path
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   UNIX only. Enables the LSF daemon startup control feature when
   \fBLSF_STARTUP_USERS\fR is also defined. Define both
   parameters when you want to allow users other than root to
   start LSF daemons.
.sp 2
   Specifies the absolute path name of the directory in which the
   LSF daemon binary files (lim, res, sbatchd, and mbatchd) are
   installed. LSF daemons are usually installed in the path
   specified by \fBLSF_SERVERDIR\fR defined in the cshrc.lsf,
   profile.lsf or lsf.conf files.
.sp 2
      \fBImportant: \fR
.sp 2
         For security reasons, you should move the LSF daemon
         binary files to a directory other than LSF_SERVERDIR or
         LSF_BINDIR. The user accounts specified by
         \fBLSF_STARTUP_USERS\fR can start any binary in the
         LSF_STARTUP_PATH.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. Only the root user account can start LSF daemons.
.sp 2
\fBLSF_STARTUP_USERS\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
LSF_STARTUP_USERS=all_admins| "user_name..."
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   UNIX only. Enables the LSF daemon startup control feature when
   \fBLSF_STARTUP_PATH\fR is also defined. Define both parameters
   when you want to allow users other than root to start LSF
   daemons. On Windows, the Platform services admin group is
   equivalent to \fBLSF_STARTUP_USERS.\fR
.sp 2
   On UNIX hosts, by default only root can start LSF daemons. To
   manually start LSF daemons, a user runs the commands lsadmin
   and badmin, which have been installed as setuid root.
   \fBLSF_STARTUP_USERS\fR specifies a list of user accounts that
   can successfully run the commands lsadmin and badmin to start
   LSF daemons.
.sp 2
   \fBall_admins\fR
.br
                 o  
                     Allows all UNIX users defined as LSF
                     administrators in the file
                     lsf.cluster.\fIcluster_name\fR to start LSF
                     daemons as root by running the lsadmin and
                     badmin commands.
.sp 2
                 o  
                     Not recommended due to the security risk of
                     a non-root LSF administrator adding to the
                     list of administrators in the
                     lsf.cluster\fI.cluster_name\fR file.
.sp 2
                 o  
                     Not required for Windows hosts because all
                     users with membership in the Platform
                     services admin group can start LSF daemons.
.sp 2
   \fB"\fIuser_name\fB..."\fR
.br
                 o  
                     Allows the specified user accounts to start
                     LSF daemons by running the lsadmin and
                     badmin commands.
.sp 2
                 o  
                     Separate multiple user names with a space.
.sp 2
                 o  
                     For a single user, do not use quotation
                     marks.
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   Not defined. Only the root user account can start LSF daemons.
.sp 2 .SH "See also"
\fBSee also\fR
.sp 2
   LSF_STARTUP_PATH
