
.ad l

.ll 72

.TH setup.config 5 September 2009" "" "Platform LSF Version 7.0.6"
.nh
\fBsetup.config\fR
.sp 2

.sp 2 .SH "About setup.config"
\fBAbout setup.config\fR
.sp 2
   The setup.config file contains options for Platform LSF
   License Scheduler installation and configuration for systems
   without Platform LSF. You only need to edit this file if you
   are installing License Scheduler as a standalone product
   without LSF.
.sp 2 .SH "Template location"
\fBTemplate location\fR
.sp 2
   A template setup.config is included in the License Scheduler
   installation script tar file and is located in the directory
   created when you uncompress and extract the installation
   script tar file. Edit the file and uncomment the options you
   want in the template file. Replace the example values with
   your own settings to specify the options for your new License
   Scheduler installation.
.sp 2
      \fBImportant: \fR
.sp 2
         The sample values in the setup.config template file are
         examples only. They are not default installation values.
.sp 2
   After the License Scheduler installation, the setup.config
   containing the options you specified is located in
   LS_TOP/7.0/install/.
.sp 2 .SH "Format"
\fBFormat\fR
.sp 2
   Each entry in setup.config has the form:
.sp 2
   NAME="STRING1 STRING2 ..."
.sp 2
   The equal sign \fR=\fR must follow each \fRNAME\fR even if no
   value follows and there should be no spaces around the equal
   sign.
.sp 2
   A value that contains multiple strings separated by spaces
   must be enclosed in quotation marks.
.sp 2
   Blank lines and lines starting with a pound sign (\fR#\fR) are
   ignored.
.sp 2 .SH "Parameters"
\fBParameters\fR
.sp 2
     o  
         LS_ADMIN
.sp 2
     o  
         LS_HOSTS
.sp 2
     o  
         LS_LICENSE_FILE
.sp 2
     o  
         LS_LMSTAT_PATH
.sp 2
     o  
         LS_TOP
.sp 2
\fBLS_ADMIN\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
   \fRLS_ADMIN\fR="\fIuser_name \fR[\fIuser_name ... \fR]"
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Lists the License Scheduler administrators. The first user
   account name in the list is the primary License Scheduler
   administrator.
.sp 2
   The primary License Scheduler administrator account is
   typically named lsadmin.
.sp 2
      \fBCAUTION: \fR
.sp 2
         You should \fInot\fR configure the root account as the
         primary License Scheduler administrator.
.sp 2 .SH "Valid Values"
\fBValid Values\fR
.sp 2
   User accounts for License Scheduler administrators must exist
   on all hosts using License Scheduler prior to installation.
.sp 2 .SH "Example"
\fBExample\fR
.sp 2
   LS_ADMINS="lsadmin user1 user2"
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   The user running the License Scheduler installation script.
.sp 2
\fBLS_HOSTS\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
   \fRLS_HOSTS\fR="\fIhost_name\fR [\fIhost_name\fR ... ]"
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Defines a list of hosts that are candidates to become License
   Scheduler master hosts. Provide at least one host from which
   the License Scheduler daemon will run.
.sp 2 .SH "Valid Values"
\fBValid Values\fR
.sp 2
   Any valid License Scheduler host name.
.sp 2 .SH "Example"
\fBExample\fR
.sp 2
   LS_HOSTS="host_name1 host_name2"
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   The local host in which the License Scheduler installation
   script is running.
.sp 2
\fBLS_LICENSE_FILE\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
   \fRLS_LICENSE_FILE\fR="/\fIpath\fR/\fIlicense_file\fR"
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Defines the full path to, and name of the License Scheduler
   license file.
.sp 2 .SH "Valid Values"
\fBValid Values\fR
.sp 2
   Any valid file name and directory path.
.sp 2 .SH "Example"
\fBExample\fR
.sp 2
   LS_LICENSE_FILE="/usr/share/ls/conf/license.dat"
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   $LS_TOP/conf/license.dat
.sp 2
\fBLS_LMSTAT_PATH\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
   \fRLS_LMSTAT_PATH\fR="/\fIpath\fR"
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Defines the full path to the lmstat program. License Scheduler
   uses lmstat to gather the FLEXnet license information for
   scheduling. This path does not include the name of the lmstat
   program itself.
.sp 2 .SH "Example"
\fBExample\fR
.sp 2
   LS_LMSTAT_PATH="/usr/bin"
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   The installation script attempts to find a working copy of
   lmstat on the current system. If it is unsuccessful, the path
   is set as blank ("").
.sp 2
\fBLS_TOP\fR
.sp 2

.sp 2 .SH "Syntax"
\fBSyntax\fR
.sp 2
   \fRLS_TOP\fR="/\fIpath\fR"
.sp 2 .SH "Description"
\fBDescription\fR
.sp 2
   Defines the full path to the top level License Shceduler
   installation directory.
.sp 2 .SH "Valid Values"
\fBValid Values\fR
.sp 2
   Must be an absolute path to a shared directory that is
   accessible to all hosts using License Scheduler. Cannot be the
   root directory (/).
.sp 2 .SH "Recommended Value"
\fBRecommended Value\fR
.sp 2
   The file system containing LS_TOP must have enough disk space
   for all host types (approximately 300 MB per host type).
.sp 2 .SH "Example"
\fBExample\fR
.sp 2
   LS_TOP="/usr/share/ls"
.sp 2 .SH "Default"
\fBDefault\fR
.sp 2
   None — required variable
