#!/bin/bash

# Find all R files and execute them.
# carl@biomatters.com

set -e

tests=$(find . -maxdepth 2 -name '*.R' -type f)

for test in ${tests}; do 
	R --no-save < ${test} 
done
/bin/rm -f *.pdf
exit 0
